SEKOIA-IO/intake-formats

- doc/overview.md
fix small typos in documentation
> feat(doc): improve documentation

- SentinelOne/deep_visibility/_meta/fields.yml
- SentinelOne/deep_visibility/ingest/parser.yml
- SentinelOne/deep_visibility/tests/event_dns.json
explain how to improve dns parser
> Deep visibility dns improvment

- Wallix/_meta/manifest.yml
- Windows/_meta/manifest.yml
Add missing description field to Windows module and Wallix module
> Modules: add missing description fields

- ISC DHCP/dhcpd/_meta/fields.yml
- ISC DHCP/dhcpd/ingest/parser.yml
- ISC DHCP/dhcpd/tests/ack.json
- ISC DHCP/dhcpd/tests/discover.json
- ISC DHCP/dhcpd/tests/release.json
- ISC DHCP/dhcpd/tests/request.json
This PR introduces a intake-format parsing strategy for most common DHCP messages.
> Introduce dhcp parsing strategy

- Stormshield/stormshield_network_security/ingest/parser.yml
- Stormshield/stormshield_network_security/tests/filter.json
Convert date fields to ISO format
> fix(stormshield): Fix wrong format for date field.

- Stormshield/stormshield_network_security/ingest/parser.yml
- Stormshield/stormshield_network_security/tests/empty_action.json
When action field is empty set the value to "log"
> fix(Stormshield): Set default value when `action` field is empty.

- McAfee/mcafee_web_gateway/ingest/parser.yml
- McAfee/mcafee_web_gateway/tests/mcafee_access_log_blocked.json
- McAfee/mcafee_web_gateway/tests/mcafee_access_log_blocked2.json
- McAfee/mcafee_web_gateway/tests/mcafee_access_log_success.json
Add the field `destination.domain` and handle the CONNECT request.
> McAfee: fix the McAfee Web Gateway parser

- McAfee/mcafee_web_gateway/event/smart-description.json
- McAfee/mcafee_web_gateway/ingest/parser.yml
- McAfee/mcafee_web_gateway/tests/mcafee_access_log_empty_destination_host.json
Handle the case when the destination host is empty
> McAfee: fix when the destination host is empty

- McAfee/mcafee_web_gateway/event/smart-description.json
Sync McAfee smart-descriptions with ones from https://github.com/SEKOIA-IO/community
> McAfee: sync smart-descriptions with one defined in community

- McAfee/mcafee_web_gateway/ingest/parser.yml
- McAfee/mcafee_web_gateway/tests/mcafee_access_log_blocked.json
- McAfee/mcafee_web_gateway/tests/mcafee_access_log_blocked2.json
- McAfee/mcafee_web_gateway/tests/mcafee_access_log_empty_destination_host.json
- McAfee/mcafee_web_gateway/tests/mcafee_access_log_success.json
add additional information about the event, the observer and the network in the parsed events
> McAfee: add more information

- Azure/azure-ad/ingest/parser.yml
- Azure/azure-ad/tests/auth.json
- Azure/azure-ad/tests/user_risk_detection.json
Add support for:
- support risk detection
- extract more info in authentication logs
Parent task:https://github.com/SekoiaLab/platform/issues/24471
> feat(Azure AD): Improve Azure AD to support user risk detection.

- SentinelOne/deep_visibility/ingest/parser.yml
- SentinelOne/deep_visibility/tests/behavioral_indicators.json
- SentinelOne/deep_visibility/tests/event_dns.json
- SentinelOne/deep_visibility/tests/file_creation.json
- SentinelOne/deep_visibility/tests/file_creation2.json
- SentinelOne/deep_visibility/tests/file_creation_missing_fields.json
- SentinelOne/deep_visibility/tests/file_deletion.json
- SentinelOne/deep_visibility/tests/file_modification.json
- SentinelOne/deep_visibility/tests/http.json
- SentinelOne/deep_visibility/tests/open_process.json
- SentinelOne/deep_visibility/tests/process_creation.json
- SentinelOne/deep_visibility/tests/process_exit.json
- SentinelOne/deep_visibility/tests/reg_key_security_changed.json
- SentinelOne/deep_visibility/tests/reg_value_create.json
- SentinelOne/deep_visibility/tests/reg_value_delete.json
- SentinelOne/deep_visibility/tests/reg_value_modified.json
- SentinelOne/deep_visibility/tests/sched_task_update.json
- SentinelOne/deep_visibility/tests/script.json
- SentinelOne/deep_visibility/tests/tcpv4.json
Simplify the way to parse the date from deepvisibility events (+ fix tests).
> DeepVisibility: fix the way to parse the date

- Cisco/cisco-wsa/ingest/parser.yml
Set the timestamp of the event from the content of the message
> Cisco: set the timestamp of the event

- Cisco/cisco-wsa/tests/event1.json
- Cisco/cisco-wsa/tests/prefixed.json
- Cisco/cisco-wsa/tests/w3c.json
add the timestamp property that are missing in the tests
> Cisco: add timestamp in the test

- SentinelOne/sentinelone/_meta/fields.yml
- SentinelOne/sentinelone/ingest/parser.yml
- SentinelOne/sentinelone/tests/activity-type-120.json
- SentinelOne/sentinelone/tests/activity-type-3016.json
- SentinelOne/sentinelone/tests/custom_rule.json
- SentinelOne/sentinelone/tests/custom_rule2.json
- SentinelOne/sentinelone/tests/threat.json
- SentinelOne/sentinelone/tests/threat2.json
- SentinelOne/sentinelone/tests/threat3.json
- SentinelOne/sentinelone/tests/user_logged_in.json
- fix(SentinelOne): fix `exclusionType` and `enabledReason` not supported by the taxonomy
- fix(SentinelOne): fix types
> sentinelone fix taxonomy

- SentinelOne/deep_visibility/ingest/parser.yml
- SentinelOne/deep_visibility/tests/behavioral_indicators.json
- SentinelOne/deep_visibility/tests/event_dns.json
- SentinelOne/deep_visibility/tests/file_creation.json
- SentinelOne/deep_visibility/tests/file_creation2.json
- SentinelOne/deep_visibility/tests/file_creation_missing_fields.json
- SentinelOne/deep_visibility/tests/file_deletion.json
- SentinelOne/deep_visibility/tests/file_modification.json
- SentinelOne/deep_visibility/tests/http.json
- SentinelOne/deep_visibility/tests/open_process.json
- SentinelOne/deep_visibility/tests/process_creation.json
- SentinelOne/deep_visibility/tests/process_exit.json
- SentinelOne/deep_visibility/tests/reg_key_security_changed.json
- SentinelOne/deep_visibility/tests/reg_value_create.json
- SentinelOne/deep_visibility/tests/reg_value_delete.json
- SentinelOne/deep_visibility/tests/reg_value_modified.json
- SentinelOne/deep_visibility/tests/sched_task_update.json
- SentinelOne/deep_visibility/tests/script.json
- SentinelOne/deep_visibility/tests/tcpv4.json
- move process title from `process.name` to `process.title`
- extract the name of the process from `process.executable`
> SentinelOne: fix process name

- Sophos/sophos/_meta/fields.yml
- Sophos/sophos/ingest/parser.yml
- Sophos/sophos/tests/url.json
- Sophos/sophos/tests/utm_accept.json
- Sophos/sophos/tests/utm_dns.json
- Sophos/sophos/tests/utm_drop.json
- Sophos/sophos/tests/xg_allow.json
Intake format to support Sophos events
> Sophos intake format

- VadeSecure/vade_secure_m365/_meta/fields.yml
- VadeSecure/vade_secure_m365/ingest/parser.yml
- VadeSecure/vade_secure_m365/tests/email.json
Add support for email's attachements
> VadeSecure: add support for attachments

- Google Cloud/Google Cloud Audit/_meta/smart-descriptions.json
Previous PR https://github.com/SEKOIA-IO/intake-formats/pull/130
> feat(Google Cloud): Move smart description from `github.com/SEKOIA-IO/Community` to `github.com/SEKOIA-IO/intake-formats`.

- Fortinet/fortigate/_meta/smart-descriptions.json
Add relationships to Fortigate intake
> fix(fortigate): add relationships

- SentinelOne/sentinelone/ingest/parser.yml
- Handle file hash in ECS fields
- Normalize user.name field
> improve S1 parser

- Azure/azure-ad/_meta/fields.yml
- Azure/azure-ad/_meta/smart-descriptions.json
- Azure/azure-ad/ingest/parser.yml
- Azure/azure-ad/tests/add_user.json
- Azure/azure-ad/tests/change_user_password.json
- Azure/azure-ad/tests/update_ststoken.json
This PR improves the AzureAD format on:
- sign-in success and failures
- user update
- device update
> Improve smart descriptions for Microsoft Azure AD

- SekoiaIO/endpoint/ingest/parser.yml
Add `event.outcome` status of the linux events of the Endpoint-Agent
> feat(endpoint-agent): add event.outcome 

- BIND/bind/_meta/smart-descriptions.json
- BIND/bind/ingest/parser.yml
- BIND/bind/tests/query_log.json
- BIND/bind/tests/query_log_cd.json
- BIND/bind/tests/query_log_dnssec.json
- BIND/bind/tests/query_log_edns_version.json
- BIND/bind/tests/query_log_no_recursion.json
- BIND/bind/tests/query_log_reverse.json
- BIND/bind/tests/query_log_tcp.json
> Add new format for Bind

- Office 365/o365/_meta/fields.yml
- Office 365/o365/ingest/parser.yml
- Office 365/o365/tests/microsoft_defender_threatintelligence_atp.json
- Office 365/o365/tests/microsoft_defender_threatintelligence_mail.json
- Office 365/o365/tests/microsoft_defender_threatintelligence_url_click.json
add support for Microsoft Defender for o365 email events
> Office365: add support for Microsoft Defender for o365 email events

- VadeSecure/vade_secure_m365/ingest/parser.yml
- VadeSecure/vade_secure_m365/tests/email.json
Extract the action done on the email in `event.action`.
> VadeSecure: extract the action done on the message

- ProofPoint/proofpoint-tap/ingest/parser.yml
Fix reply_to address as the original data is an array
> ProofPointTAP: fix reply_to.address

- CrowdStrike/crowdstrike_falcon/_meta/smart-descriptions.json
Added some smart description and relationships for Crowdstrike Detection summary event.
> feat(crowdstrike): Smart description and relationships

- Beats/auditbeat/ingest/parser.yml
Change log.hostname to be based on host.name instead of beat.name
> Fix(Auditbeat): change log.hostname

- SentinelOne/deep_visibility/_meta/fields.yml
- SentinelOne/deep_visibility/_meta/smart-descriptions.json
- SentinelOne/deep_visibility/ingest/parser.yml
- SentinelOne/deep_visibility/tests/http.json
- fix(s1/deepvisibility): Remove duplicated field `deepvisibility.event.type`
- fix(s1/deepvisibility): Remove duplicated field `deepvisibility.process.executable.name`
- fix(s1/deepvisibility): Add some relationships to `process` smart-descriptions
- fix(s1/deepvisibility): Fix tests
- feat(s1/deepvisibility): Add missing smart descriptions' relationships
Related issue: https://github.com/SekoiaLab/platform/issues/32464
Part of: https://github.com/SekoiaLab/platform/issues/32475
> fix s1 deepvisibility smart descriptions relationships

- SentinelOne/deep_visibility/_meta/fields.yml
- SentinelOne/deep_visibility/_meta/smart-descriptions.json
Related to:
- Fix: https://github.com/SekoiaLab/platform/issues/32464
> feat(S1/DeepVisibility): Add more relationships

- Sophos/sophos edr/tests/event_disk_non_encrypted.json
- Sophos/sophos edr/tests/event_encryption_information.json
- Sophos/sophos edr/tests/event_encryption_suspended.json
- Sophos/sophos edr/tests/event_key_received.json
- Sophos/sophos edr/tests/event_outlook_plugin.json
- Sophos/sophos edr/tests/event_registered.json
- Sophos/sophos edr/tests/event_scan_complete.json
- Sophos/sophos edr/tests/event_update_failure.json
- Sophos/sophos edr/tests/event_update_reboot_required.json
- Sophos/sophos edr/tests/event_update_success.json
- Sophos/sophos edr/tests/event_user_auto_created.json
- Sophos/sophos edr/tests/event_webfiltering.json
1. Diff tests result to see if output is ok
3. Automatically fix expected
Parent task:
- https://github.com/SekoiaLab/platform/issues/32475
> fix tests for Sophos EDR

- SkyhighSecurity/skyhigh_secure_web_gateway/_meta/smart-descriptions.json
Parent task:
- https://github.com/SekoiaLab/platform/issues/31026
> feat(skyhigh): improve smart description

- HarfangLab/harfanglab/ingest/parser.yml
- HarfangLab/harfanglab/tests/process.json
- HarfangLab/harfanglab/tests/process3.json
This is a fix for:
- https://github.com/SekoiaLab/platform/issues/29515
> fix(harfanglab): Add missing `process.parent.name`

- SkyhighSecurity/skyhigh_secure_web_gateway/_meta/smart-descriptions.json
Parent task:
- https://github.com/SekoiaLab/platform/issues/31026
> feat(SkyhighSecurity/SWG): Improve main smart description relationships

- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/IP_SEC.STANDARD.json
- Fortinet/fortigate/tests/LOGOUT.STANDARD.json
- Fortinet/fortigate/tests/ROLL-LOG.STANDARD.json
- Fortinet/fortigate/tests/WAD.STANDARD.json
- Fortinet/fortigate/tests/tunnel.json
- Fortinet/fortigate/tests/tunnel_statistics.CSV.json
- Fortinet/fortigate/tests/vpn.STANDARD.json
I removed `log.description` fields, the other non ecs fields were removed in the previous PR
parent task: #26009
> remove some non ecs fields

- SkyhighSecurity/skyhigh_secure_web_gateway/_meta/smart-descriptions.json
- fix(Skyhigh/SWG): fix `event.type` for smart-descriptions
Parent task:
- https://github.com/SekoiaLab/platform/issues/32995
> fix(skyhigh/swg) Event type in smart description

- SkyhighSecurity/skyhigh_secure_web_gateway/_meta/smart-descriptions.json
Fix for issue:
- https://github.com/SekoiaLab/platform/issues/33019
Parent task:
- https://github.com/SekoiaLab/platform/issues/32995
> fix(Skyhigh/SWG): fix condition for main smart-description

- Sophos/sophos edr/ingest/parser.yml
- Sophos/sophos edr/tests/event_disk_non_encrypted.json
- Sophos/sophos edr/tests/event_encryption_information.json
- Sophos/sophos edr/tests/event_encryption_suspended.json
- Sophos/sophos edr/tests/event_key_received.json
- Sophos/sophos edr/tests/event_outlook_plugin.json
- Sophos/sophos edr/tests/event_registered.json
- Sophos/sophos edr/tests/event_scan_complete.json
- Sophos/sophos edr/tests/event_update_failure.json
- Sophos/sophos edr/tests/event_update_reboot_required.json
- Sophos/sophos edr/tests/event_update_success.json
- Sophos/sophos edr/tests/event_user_auto_created.json
- Sophos/sophos edr/tests/event_webfiltering.json
> Sophos: add host.name

- SkyhighSecurity/skyhigh_secure_web_gateway/_meta/smart-descriptions.json
- SkyhighSecurity/skyhigh_secure_web_gateway/ingest/parser.yml
- SkyhighSecurity/skyhigh_secure_web_gateway/tests/mcafee_access_log_success.json
- SkyhighSecurity/skyhigh_secure_web_gateway/tests/skyhigh_swg.json
- SkyhighSecurity/skyhigh_secure_web_gateway/tests/skyhigh_swg_block.json
Parent task:
- https://github.com/SekoiaLab/platform/issues/32995
> fix(Skyhigh/SWG): fix smart-description broken because `event.type.0` is not currently supported

- Retarus/retarus_email_security/ingest/parser.yml
- Retarus/retarus_email_security/tests/event_no_sender.json
Fix the parser when the sender is empty (and not null)
> Retarus: fix parser when sender is empty

- AWS/aws-flow-logs/ingest/parser.yml
- AWS/aws-flow-logs/tests/accept_structured.json
- AWS/aws-flow-logs/tests/reject_structured.json
Extend the Flowlogs parser with json-formatted events
> AWS: add support for flowlogs json formatted events

- ProofPoint/proofpoint-pod/_meta/fields.yml
- ProofPoint/proofpoint-pod/_meta/smart-descriptions.json
- ProofPoint/proofpoint-pod/ingest/parser.yml
- ProofPoint/proofpoint-pod/tests/test_message.json
- ProofPoint/proofpoint-pod/tests/test_message2.json
- ProofPoint/proofpoint-pod/tests/test_message3.json
Add the envelope sender and recipients in the event.
Add a smart-description.
> Proofpoint: Add smtp envelope information

- Trend Micro/deep-security/_meta/fields.yml
- Trend Micro/deep-security/_meta/smart-descriptions.json
- Trend Micro/deep-security/ingest/parser.yml
- Trend Micro/deep-security/tests/ApacheDOS.json
- Trend Micro/deep-security/tests/DeviceControl.json
- Trend Micro/deep-security/tests/FirewallEventLog.json
- Trend Micro/deep-security/tests/IntrusionPrevention.json
- fix(Trend Micro/DeepVisibility): Wrongly called `CEF` fields.
- feat(Trend Micro/DeepVisibility): Improve basic smart description.
> fix trendmicro deep security

- Azure/azure-ad/ingest/parser.yml
- Azure/azure-ad/tests/add_domain.json
- Azure/azure-ad/tests/add_member_to_group.json
- Azure/azure-ad/tests/add_service_principal_failure.json
- Azure/azure-ad/tests/add_user.json
- Azure/azure-ad/tests/auth.json
- Azure/azure-ad/tests/change_user_password.json
- Azure/azure-ad/tests/empty_geolocalisation.json
- Azure/azure-ad/tests/remove_domain.json
- Azure/azure-ad/tests/sign-in_activity.json
- Azure/azure-ad/tests/sign-in_activity2.json
- Azure/azure-ad/tests/update_ststoken.json
- Azure/azure-ad/tests/user_risk_detection.json
Related issue:
- https://github.com/SekoiaLab/platform/issues/34288
> feat(azure/ad): Add timestamp field

- Forcepoint/forcepoint-swg/ingest/parser.yml
- Forcepoint/forcepoint-swg/tests/test_transaction_permitted.json
Extract the username and the domain from the user path
> Forcepoint: split username and domain

- Beats/auditbeat/ingest/parser.yml
- Beats/auditbeat/tests/example1.json
- Beats/auditbeat/tests/example10.json
- Beats/auditbeat/tests/example11.json
- Beats/auditbeat/tests/example12.json
- Beats/auditbeat/tests/example13.json
- Beats/auditbeat/tests/example2.json
- Beats/auditbeat/tests/example3.json
- Beats/auditbeat/tests/example4.json
- Beats/auditbeat/tests/example5.json
- Beats/auditbeat/tests/example6.json
- Beats/auditbeat/tests/example7.json
- Beats/auditbeat/tests/example8.json
- Beats/auditbeat/tests/example9.json
Temporary fix for:
- https://github.com/SekoiaLab/platform/issues/34239
- https://github.com/SekoiaLab/platform/issues/34514
> fix(Beats/Auditbeat): Fix missing `event` fields.

- Fortinet/fortigate/_meta/fields.yml
- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/DLP.CEF.json
- Fortinet/fortigate/tests/IPS.CEF.json
- Fortinet/fortigate/tests/WAF.CEF.json
- Fortinet/fortigate/tests/anomaly.CEF-2.json
- Fortinet/fortigate/tests/antivirus.CEF-2.json
- Fortinet/fortigate/tests/antivirus.CEF.json
- Fortinet/fortigate/tests/application.CEF.json
- Fortinet/fortigate/tests/dns.CSV.json
- Fortinet/fortigate/tests/email-spamfilter.CEF.json
- Fortinet/fortigate/tests/hostname.STANDARD.json
- Fortinet/fortigate/tests/ping.json
- Fortinet/fortigate/tests/traffic_forward-RDP.CEF.json
- Fortinet/fortigate/tests/traffic_forward.CEF-2.json
- Fortinet/fortigate/tests/traffic_forward.CEF-3.json
- Fortinet/fortigate/tests/traffic_forward.CEF.json
- Fortinet/fortigate/tests/traffic_forward.STANDARD_2.json
- Fortinet/fortigate/tests/traffic_forward_FTNTFGTtz.CEF.json
- Fortinet/fortigate/tests/webfilter.CEF.json
- fix dns custom fields
- lowercase network fields
- handle backslashes in usernames
> Fortigate: several fixes

- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/icmp6.json
- Fortinet/fortigate/tests/icmp_CEF.json
- Fortinet/fortigate/tests/ping.json
- Fortinet/fortigate/tests/ssl_new_con.CEF.json
- Fortinet/fortigate/tests/traffic_forward-RDP.CEF.json
- Fortinet/fortigate/tests/traffic_forward.CEF-2.json
- Fortinet/fortigate/tests/traffic_forward.CEF-3.json
- Fortinet/fortigate/tests/traffic_forward.CEF.json
- Fortinet/fortigate/tests/traffic_forward.CSV.json
- Fortinet/fortigate/tests/traffic_forward.STANDARD.json
- Fortinet/fortigate/tests/traffic_forward.STANDARD_2.json
- Fortinet/fortigate/tests/traffic_nat.STANDARD.json
- Fortinet/fortigate/tests/tunnel.json
- Fortinet/fortigate/tests/tunnel_statistics.CSV.json
- Fortinet/fortigate/tests/webfilter.CEF.json
- compute network.bytes (backward compatibilty)
- handle 'N/A' as username
> Fortinet: add network.bytes and fix usernames

- BIND/bind/tests/query_log.json
- BIND/bind/tests/query_log_cd.json
- BIND/bind/tests/query_log_dnssec.json
- BIND/bind/tests/query_log_edns_version.json
- BIND/bind/tests/query_log_no_recursion.json
- BIND/bind/tests/query_log_reverse.json
- BIND/bind/tests/query_log_tcp.json
- Cloudflare/dns_logs/tests/dns_type_1.json
- Cloudflare/dns_logs/tests/dns_type_2.json
- Cloudflare/dns_logs/tests/dns_type_28.json
- Cloudflare/dns_logs/tests/dns_type_65535.json
- Infoblox/ddi/tests/query_log.json
- Infoblox/ddi/tests/query_log_cd.json
- Infoblox/ddi/tests/query_log_dnssec.json
- Infoblox/ddi/tests/query_log_edns_version.json
- Infoblox/ddi/tests/query_log_no_recursion.json
- Infoblox/ddi/tests/query_log_reverse.json
- Infoblox/ddi/tests/query_log_tcp.json
fix dns tests after application of the dns finalizer
> Formats: fix dns tests

- SentinelOne/deep_visibility/tests/event_dns.json
Fix failing test due to dns enrichment.
> SentinelOne: fix tests

- utils/create_test.py
- utils/poetry.lock
- utils/pyproject.toml
Add a script to create new test in a format:
```sh
$ cd utils
$ poetry run python3 create_test.py ../My-module/my-format/tests/test1.json "<raw event>"
$ cat /tmp/raw-event.txt | poetry run python3 create_test.py ../My-module/my-format/tests/test2.json
```
> Tooling: add script to create new test

- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/Configuration_changed.CEF.json
- Fortinet/fortigate/tests/DNS.STANDARD.json
- Fortinet/fortigate/tests/DNS2.STANDARD.json
- Fortinet/fortigate/tests/dns.CSV.json
- Fortinet/fortigate/tests/event_log_user_subtype.CEF.json
- Fortinet/fortigate/tests/ssl_new_con.CEF.json
- Fortinet/fortigate/tests/vpn.STANDARD.json
Apply several fixes in the parser are detecting errors.
> Fortigate: Multiple fixes

- SekoiaIO/activity_log/ingest/parser.yml
Fix error parsing for SEKOIA.IO Activity Logs
> fix(sekoiaio-activity-logs: fix error parsing

- Okta/okta-system-logs/_meta/fields.yml
- Okta/okta-system-logs/ingest/parser.yml
- Okta/okta-system-logs/tests/test_auth_via_idp.json
- Okta/okta-system-logs/tests/test_auth_via_mfa.json
- Okta/okta-system-logs/tests/test_authentication_sso.json
- Okta/okta-system-logs/tests/test_authentication_sso_failure.json
- Okta/okta-system-logs/tests/test_login.json
- Okta/okta-system-logs/tests/test_send_factor.json
- Okta/okta-system-logs/tests/test_update_account.json
This change aim to parse Okta outcome fields : 
`outcome.reason` : The reason of the outcome.
`outcome.result` : The result of the outcome.
> fix(okta): adding outcome fields

- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/vpn_na_ip.STANDARD.json
Fix the format to discard ips with N/A values
> Fortigate: handle N/A for ips

- CrowdStrike/crowdstrike_falcon/_meta/fields.yml
- CrowdStrike/crowdstrike_falcon/ingest/parser.yml
- CrowdStrike/crowdstrike_falcon/tests/detection_summary_event.json
extract the severity and the severity name from the event
> CrowdStrike: extract the severity and the severity name from the event

- Fortinet/fortigate/_meta/smart-descriptions.json
- Fix some existing smart-descriptions
- add new wide-catch smart-descriptions
> Fortigate: improve smart-descriptions

- SekoiaIO/endpoint/_meta/smart-descriptions.json
Add smart description for events related to agent inactivity.
> feat: Agent inactivity smart description

- Tehtris/tehtris-edr/_meta/fields.yml
- Tehtris/tehtris-edr/_meta/smart-descriptions.json
- Tehtris/tehtris-edr/ingest/parser.yml
- Tehtris/tehtris-edr/tests/test_antivirus_alert.json
Add antivirus total and positives fields to tehtris-edr parser.
> Add tehtris antivirus fields

- Azure/azure-front-door/ingest/parser.yml
- Azure/azure-front-door/tests/test_accesslog.json
- Azure/azure-front-door/tests/test_healthprobe.json
change event categorization from network to web
> Azure: fix the categorization of events from azure-front-door

- Netskope/netskope_events/_meta/fields.yml
- Netskope/netskope_events/ingest/parser.yml
- Netskope/netskope_events/tests/test_audit_log_deleted_inline_policy.json
- Netskope/netskope_events/tests/test_audit_log_edit_admin_record.json
- Netskope/netskope_events/tests/test_audit_log_login_failed.json
- Netskope/netskope_events/tests/test_audit_log_login_successful.json
- Netskope/netskope_events/tests/test_audit_log_logout_successful.json
- Netskope/netskope_events/tests/test_audit_log_password_change_successful.json
- Netskope/netskope_events/tests/test_connection_log.json
- Netskope/netskope_events/tests/test_dlp_incident.json
- Netskope/netskope_events/tests/test_malware_alert.json
- Netskope/netskope_events/tests/test_nspolicy_log.json
- Netskope/netskope_events/tests/test_user_alert.json
- Add support for DLP events
- fix the parsing of the timestamp
> Netskope: add DLP events + fix timestamp

- utils/conftest.py
Enclosed the module taxonomy in the format taxonomy when validating the format with tests
> Tooling: add module taxonomy when testing

- Beats/auditbeat/tests/example1.json
- Beats/auditbeat/tests/example10.json
- Beats/auditbeat/tests/example11.json
- Beats/auditbeat/tests/example12.json
- Beats/auditbeat/tests/example13.json
- Beats/auditbeat/tests/example2.json
- Beats/auditbeat/tests/example3.json
- Beats/auditbeat/tests/example4.json
- Beats/auditbeat/tests/example5.json
- Beats/auditbeat/tests/example6.json
- Beats/auditbeat/tests/example7.json
- Beats/auditbeat/tests/example8.json
- Beats/auditbeat/tests/example9.json
- Cloudflare/firewall_events/tests/block.json
- Panda Security/Aether/tests/Retrieve_Security _Events_for_Devices_indicator_type_detections_3.json
Fix the tests after the last update of the engine (removing empty structure).
> Tests: fix failing test

- Cisco/cisco-meraki/_meta/smart-descriptions.json
- Cisco/cisco-meraki/ingest/parser.yml
- Cisco/cisco-meraki/tests/test_dhcp_lease.json
- Cisco/cisco-meraki/tests/test_dhcp_no_offer.json
- Cisco/cisco-meraki/tests/test_events_anyconnect_vpn_auth_failure.json
- Cisco/cisco-meraki/tests/test_events_anyconnect_vpn_auth_success.json
- Cisco/cisco-meraki/tests/test_events_anyconnect_vpn_connect_1.json
- Cisco/cisco-meraki/tests/test_events_anyconnect_vpn_connect_2.json
- Cisco/cisco-meraki/tests/test_events_anyconnect_vpn_connection_success.json
- Cisco/cisco-meraki/tests/test_events_anyconnect_vpn_session_manager.json
- Cisco/cisco-meraki/tests/test_events_content_filtering_block.json
- Cisco/cisco-meraki/tests/test_flows_allow.json
- Cisco/cisco-meraki/tests/test_flows_block.json
- Cisco/cisco-meraki/tests/test_ip_flow_end.json
- Cisco/cisco-meraki/tests/test_ip_flow_start.json
- Cisco/cisco-meraki/tests/test_urls_1.json
- Cisco/cisco-meraki/tests/test_urls_2.json
- Cisco/cisco-meraki/tests/test_urls_3.json
Add more smart-descriptions.
Add some improvement to the parser
> Cisco: Improve Cisco Meraki smart-descriptions and parser

- utils/test_formats.py
Allow the coverage to be equal to 75.
> Test: fix the coverage threshold to >= 75

- Cisco/cisco-secure-web-appliance/ingest/parser.yml
- Cisco/cisco-secure-web-appliance/tests/test_export_files.json
- Cisco/cisco-secure-web-appliance/tests/test_export_to_database.json
Fix conditions to avoid error parsing on system messages
> Cisco: Fix Cisco Secure Web Appliance parser

- Office 365/o365/_meta/fields.yml
- Office 365/o365/ingest/parser.yml
Adding fields "VirusInfo" and "VirusVendor" to 0365 parser
> Updating O365 parser

- SonicWall/sonicwall-fw/_meta/smart-descriptions.json
Minor fixes to debug sonicwall smart descriptions
> Fix/sonic wall/fw/smart descriptions

- Office 365/o365/ingest/parser.yml
- Office 365/o365/tests/ad.json
- Office 365/o365/tests/compliancemanager-scorechange.json
- Office 365/o365/tests/exchange_event1.json
- Office 365/o365/tests/file_previewed.json
- Office 365/o365/tests/file_sync_download_full.json
- Office 365/o365/tests/file_visited.json
- Office 365/o365/tests/microsoft_defender_threatintelligence_atp.json
- Office 365/o365/tests/microsoft_defender_threatintelligence_mail.json
- Office 365/o365/tests/microsoft_defender_threatintelligence_url_click.json
- Office 365/o365/tests/teams_message_has_link.json
- Office 365/o365/tests/update_group.json
- Office 365/o365/tests/update_user.json
- Office 365/o365/tests/update_user_empty_source_ip.json
- Office 365/o365/tests/user_logged_in.json
- Office 365/o365/tests/user_login_failed.json
fix the field used to extract the timestamp
> Office365: fix the field used to extract the timestamp

- NetFlow/netflow/ingest/parser.yml
Use inbound and outbound values to be consistent with others parsers
> NetFlow: fix network.direction

- Microsoft/microsoft-365-defender/_meta/fields.yml
- Microsoft/microsoft-365-defender/_meta/smart-descriptions.json
- Microsoft/microsoft-365-defender/ingest/parser.yml
- Microsoft/microsoft-365-defender/tests/test_device_info_event_add_join.json
- Microsoft/microsoft-365-defender/tests/test_device_info_event_hybrid_join.json
- Microsoft/microsoft-365-defender/tests/test_device_logon_events.json
- Microsoft/microsoft-365-defender/tests/test_device_network_events.json
- Microsoft/microsoft-365-defender/tests/test_device_network_info.json
- Microsoft/microsoft-365-defender/tests/test_device_process_events.json
- Microsoft/microsoft-365-defender/tests/test_device_registry_events.json
- Add smart-description for Device info events
- Add more tests
> Microsoft: Improve Microsoft 365 Defender format

- Cloudflare/audit_logs/_meta/smart-descriptions.json
- Cloudflare/audit_logs/ingest/parser.yml
- Cloudflare/audit_logs/tests/test_gateway_create.json
- Cloudflare/audit_logs/tests/test_gateway_create_location.json
- Cloudflare/audit_logs/tests/test_gateway_update.json
- Cloudflare/audit_logs/tests/test_job_create.json
- Cloudflare/audit_logs/tests/test_job_update.json
Variable did not have the correct name.
> cloudflare.ActionType to event.action

- AWS/aws-guardduty/ingest/parser.yml
Modification of deletion fields
> AWS: GuardDuty fixes

- Cloudflare/access_requests/_meta/smart-descriptions.json
- Cloudflare/gateway_http/_meta/smart-descriptions.json
- Cloudflare/gateway_http/ingest/parser.yml
- Cloudflare/gateway_http/tests/test_http.json
> Fix/c loudflare/access request/country iso code

- CEF/cef/ingest/parser.yml
- CEF/cef/tests/pan_ngfw_auth_cef.json
- CEF/cef/tests/pan_ngfw_file_cef.json
- CEF/cef/tests/pan_ngfw_hip_match_cef.json
- CEF/cef/tests/pan_ngfw_iptag_cef.json
- CEF/cef/tests/pan_ngfw_sctp_cef.json
- CEF/cef/tests/pan_ngfw_threat_cef.json
- CEF/cef/tests/pan_ngfw_traffic_cef.json
- CEF/cef/tests/pan_ngfw_url_cef.json
- CEF/cef/tests/pan_ngfw_userid_cef.json
- Cisco/cisco-esa/ingest/parser.yml
- SonicWall/sonicwall-fw/ingest/parser.yml
> fix(formats): Fix typo in CEF formats

- Microsoft/microsoft-365-defender/_meta/fields.yml
- Microsoft/microsoft-365-defender/ingest/parser.yml
- Microsoft/microsoft-365-defender/tests/test_device_file_certificate_info.json
wrong syntax was used:
**foo: "foo"**
foo.bar: "foo.bar"
replaced by
**foo.name: "foo"**
foo.bar: "foo.bar"
> fix(Microsoft/Defender): item assignement issue

- SentinelOne/cloud_funnel2.0/_meta/fields.yml
- SentinelOne/cloud_funnel2.0/tests/linux_process_processcreation.json
- SentinelOne/cloud_funnel2.0/tests/process_processcreation.json
> fix(s1/cloudfunnel): fix wrong field type for ` deepvisibility.process.target.user.name`

- Cisco/cisco-secure-firewall/_meta/fields.yml
- Cisco/cisco-secure-firewall/ingest/parser.yml
- Cisco/cisco-secure-firewall/tests/test_ASA_609002.json
Since I don't know the format used by Cisco, I suggest that we move to a custom field
> fix(Cisco/FTD): move event duration to a custom field

- WatchGuard/watchguard-firebox/ingest/parser.yml
- WatchGuard/watchguard-firebox/tests/dpi_http_1.json
fix `could not convert string "0.001407 sec(s)" to float`
> fix(watchguard): remove string from duration field

- SonicWall/sonicwall-fw/ingest/parser.yml
Related to [#42150](https://github.com/SekoiaLab/platform/issues/42150)
> Sonic wall/fix/full custom fields parser

- Retarus/_meta/manifest.yml
Change the uuid of the Retarus module (duplicated with the uuid of the Beats module)
> Retarus: fix the module uuid

- Citrix/citrix-adc/CHANGELOG.md
- Citrix/citrix-adc/_meta/manifest.yml
- Add the beta flag to the format name
- Add the old name of the product in the name of the format
- Initialize the changelog document
> Citrix: some fixes

- Github/github-audit-logs/_meta/manifest.yml
> Github: add the beta flag

- utils/new_intake/{{cookiecutter.intake_slug}}/CHANGELOG.md
Create an empty changelog.md along with creating a new format by  ```python3 generate.py new-format```
> Create CHANGELOG automatically

- Palo Alto Networks/paloalto-ngfw/ingest/parser.yml
- Palo Alto Networks/paloalto-ngfw/tests/fix_bug_with_int.json
- Palo Alto Networks/paloalto-ngfw/tests/fix_bug_without_int.json
Hello, This's a fix of the PaloAlto warning on some events.
Parent issue : #43970
> Fix the problem of some int fields that gets str values

- SekoiaIO/endpoint/_meta/fields.yml
- SekoiaIO/endpoint/ingest/parser.yml
- SekoiaIO/endpoint/tests/linux_auth.json
- SekoiaIO/endpoint/tests/linux_auth2.json
- SekoiaIO/endpoint/tests/linux_auth3.json
- SekoiaIO/endpoint/tests/windows_auth.json
- SekoiaIO/endpoint/tests/windows_auth2.json
> Feat sekoiaio agent add authentication logic

- Beats/winlogbeat/tests/auth.json
- Beats/winlogbeat/tests/auth2.json
> feat(Beats/Winlogbeat): Add tests

- .github/workflows/main.yml
- utils/checks.py
Update to Python3.10 typing style checks.py to be  compatible with Pydantic2.0
> Utils: fix typing

- SentinelOne/cloud_funnel2.0/_meta/fields.yml
- SentinelOne/cloud_funnel2.0/ingest/parser.yml
- SentinelOne/cloud_funnel2.0/tests/commandscript.json
- SentinelOne/cloud_funnel2.0/tests/dns_dnsresolved.json
- SentinelOne/cloud_funnel2.0/tests/file_filedeletion.json
- SentinelOne/cloud_funnel2.0/tests/group_groupcreation.json
- SentinelOne/cloud_funnel2.0/tests/indicators_behavioralindicators.json
- SentinelOne/cloud_funnel2.0/tests/linux_process_processcreation.json
- SentinelOne/cloud_funnel2.0/tests/logins_login_failure.json
- SentinelOne/cloud_funnel2.0/tests/logins_login_success.json
- SentinelOne/cloud_funnel2.0/tests/process_processcreation.json
- SentinelOne/cloud_funnel2.0/tests/registry_binary.json
- SentinelOne/cloud_funnel2.0/tests/registry_security.json
- SentinelOne/cloud_funnel2.0/tests/scheduledtask_taskregister.json
- SentinelOne/cloud_funnel2.0/tests/scheduledtask_taskstart.json
- SentinelOne/deep_visibility/ingest/parser.yml
Fix Cloud funnel 1.0 (formely DeepVisibility) and Cloud funnel 2.0 according to the failing checks seen in these formats
> SentinelOne: Fix formats according to the verification script

- Palo Alto Networks/paloalto-ngfw/_meta/fields.yml
- Palo Alto Networks/paloalto-ngfw/ingest/parser.yml
- Palo Alto Networks/paloalto-ngfw/tests/globalprotect_csv_2.json
- Palo Alto Networks/paloalto-ngfw/tests/wildfire1_json.json
- Declare the custom root field paloalto in the taxonomy.
- Fix issue about null byte in the event.
> PaloAlto: fix paloalto custom field

- Trellix/trellix-epo/_meta/manifest.yml
- Trellix/trellix-epo/ingest/parser.yml
- Trellix/trellix-epo/tests/epo_event.json
- add user.name and user.target.name from source.user.name and destination.user.name
- add the alpha flag
> Trellix: add alpha flag

- Jumpcloud/jumpcloud-directory-insights/_meta/manifest.yml
- fix the slug
- update the uuid (already used)
- add the beta flag
> Jumpcloud: some changes

- CrowdStrike/crowdstrike_falcon/ingest/parser.yml
- CrowdStrike/crowdstrike_falcon/tests/detection_summary_event1.json
Hi @squioc,
I have added two fields `IOCValue` and `PatternDispositionDescription`, also i have seen that `FileName` exist as `process.name` and `FilePath` exist as `process.working_directory`
Parent Issue : [#42101](https://github.com/SekoiaLab/platform/issues/42101)
> Add PatternDispositionDescription and IOCValue fields

- VadeSecure/vade_secure_m365/_meta/fields.yml
- VadeSecure/vade_secure_m365/ingest/parser.yml
- VadeSecure/vade_secure_m365/tests/email.json
- VadeSecure/vade_secure_m365/tests/email_action_move.json
- VadeSecure/vade_secure_m365/tests/email_with_attachment.json
> update(vadem365): parse whitelist field

- VadeSecure/vade_secure_m365/_meta/smart-descriptions.json
vadesecure.campaign.actions.action rather than vadesecure.campaign.actions.0.action
> smartdesc fix

- Cisco/cisco-esa/ingest/parser.yml
- Cisco/cisco-esa/tests/test_ingest_log3.json
fix of the first error on ESAUrlDetails
> fix error parsing Cisco ESA bug esaurldetails

- Trellix/README.md
- Trellix/trellix-epo/CHANGELOG.md
- Trellix/trellix-epo/_meta/smart-descriptions.json
- Trellix/trellix-epo/ingest/parser.yml
- Trellix/trellix-epo/tests/epo_event.json
- add a smart-description
- add event.category and event.type
> Trellix: some fixes

- Okta/okta-system-logs/CHANGELOG.md
- Okta/okta-system-logs/_meta/fields.yml
- Okta/okta-system-logs/ingest/parser.yml
- Okta/okta-system-logs/tests/test_target.json
Hello ! Here is a little PR to add dtHash field because we need it to create detection rules.
> feat(okta): adding dtHash

- Fortinet/fortiproxy/_meta/fields.yml
- Fortinet/fortiproxy/ingest/parser.yml
- Fortinet/fortiproxy/tests/referralurl.json
Add parsing of referralurl (client request https://sekoia8055.zendesk.com/agent/tickets/1248)
> add fortinetproxy referralurl field

- Google Cloud/google-drive-reports/_meta/smart-descriptions.json
- Add smart desc to Google reports parser
> Add smart desc

- Cisco/cisco-secure-firewall/_meta/smart-descriptions.json
- Cisco/cisco-secure-firewall/ingest/parser.yml
- Cisco/cisco-secure-firewall/tests/test_ASA_106012.json
- Cisco/cisco-secure-firewall/tests/test_ASA_106015.json
- Cisco/cisco-secure-firewall/tests/test_ASA_106023.json
- Cisco/cisco-secure-firewall/tests/test_ASA_106100.json
- Cisco/cisco-secure-firewall/tests/test_ASA_313005.json
- Cisco/cisco-secure-firewall/tests/test_ASA_716058.json
- Cisco/cisco-secure-firewall/tests/test_ASA_716059.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722011.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722012.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722023.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722023_2.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722028.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722032.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722033.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722034.json
- Cisco/cisco-secure-firewall/tests/test_ASA_722037.json
- Cisco/cisco-secure-firewall/tests/test_ASA_725007.json
- Cisco/cisco-secure-firewall/tests/test_group_2.json
- Cisco/cisco-secure-firewall/tests/test_group_3.json
- Add `event.category` and `event.type` for anyconnect logs
- Add new smart-descriptions.
> Cisco: add several improvements

- Windows/windows/ingest/parser.yml
Add missed review suggestion https://github.com/SEKOIA-IO/intake-formats/pull/748#discussion_r1335932085
> fix(windows): `event.Message` add strip to json check as suggested by @squioc

- Citrix/citrix-adc/CHANGELOG.md
- Citrix/citrix-adc/_meta/smart-descriptions.json
- Citrix/citrix-adc/ingest/parser.yml
- Citrix/citrix-adc/tests/test_aaatm.json
- Citrix/citrix-adc/tests/test_snmp_log.json
- Citrix/citrix-adc/tests/test_sslvpn_log_1.json
- add support for aaatm messages
- refactor to manage unknown audit logs
- add new smart-descriptions
- fix conditions in smart-descriptions
> Citrix: add support for AAATM messages

- RSA/rsa-securid/_meta/fields.yml
- RSA/rsa-securid/_meta/smart-descriptions.json
- RSA/rsa-securid/ingest/parser.yml
- RSA/rsa-securid/tests/test_audit_admin_event.json
- RSA/rsa-securid/tests/test_audit_admin_event2.json
- RSA/rsa-securid/tests/test_audit_admin_event3.json
- RSA/rsa-securid/tests/test_audit_admin_event4.json
- RSA/rsa-securid/tests/test_audit_runtime_event2.json
- RSA/rsa-securid/tests/test_audit_runtime_event3.json
- RSA/rsa-securid/tests/test_system_event.json
- fix smart-descriptions for failed login
- move the event.outcome to a custom field
> RSA: Improve smart-descriptions and parsing

- Okta/okta-system-logs/_meta/smart-descriptions.json
https://github.com/SekoiaLab/platform/issues/45719
> update okta sd

- Zscaler/zscaler-zia/_meta/smart-descriptions.json
Add result (allowed or blocked) of a domain access request
> Zscaler-Update smart-descriptions.json

- AWS/aws-guardduty/_meta/manifest.yml
- Citrix/citrix-adc/_meta/manifest.yml
- Trend Micro/trend-micro-apex-one/_meta/manifest.yml
- VadeSecure/vade_cloud/_meta/manifest.yml
Guardduty, Vade Cloud, Trend micro Apex one, citrix ADC
> Remove Beta Label

- utils/conftest.py
- utils/test_formats.py
> feat(utils): add `--fix-missing-fields` to auto-fix taxonomy

- Trend Micro/email-security/CHANGELOG.md
- Trend Micro/email-security/_meta/manifest.yml
This should make it more clear which type of logs we collect here.
> Fix datasource description

- Windows/windows/ingest/parser.yml
- Windows/windows/tests/wrong-startswith.json
This reverts commit 61616d55f05ad0ccf784a0b10a17472a42ed520d :sob:
> Windows: add patch about bad syslog config

- HarfangLab/harfanglab/_meta/smart-descriptions.json
add smart-descriptions for agentlog and diverload events
> Harfanglab: add new smart-descriptions

- F5 Networks/f5-big-ip/ingest/parser.yml
- F5 Networks/f5-big-ip/tests/test_afm_1.json
- F5 Networks/f5-big-ip/tests/test_afm_2.json
- F5 Networks/f5-big-ip/tests/test_afm_3.json
- F5 Networks/f5-big-ip/tests/test_psm_1.json
- F5 Networks/f5-big-ip/tests/test_psm_2.json
- F5 Networks/f5-big-ip/tests/test_request.json
- F5 Networks/f5-big-ip/tests/test_rule4.json
- F5 Networks/f5-big-ip/tests/test_successful_request.json
- F5 Networks/f5-big-ip/tests/test_wget.json
Extract the source user and change the destination field for the protocol name.
> F5: extract some additional fields

- F5 Networks/f5-big-ip/ingest/parser.yml
- F5 Networks/f5-big-ip/tests/test_afm_1.json
- F5 Networks/f5-big-ip/tests/test_afm_2.json
- F5 Networks/f5-big-ip/tests/test_afm_3.json
- F5 Networks/f5-big-ip/tests/test_psm_1.json
- F5 Networks/f5-big-ip/tests/test_psm_2.json
- F5 Networks/f5-big-ip/tests/test_request.json
- F5 Networks/f5-big-ip/tests/test_successful_request.json
- F5 Networks/f5-big-ip/tests/test_wget.json
Introduce fields that were filled in the previous implementation.
> F5 Network: improve backward compatibility

- Broadcom/secure-web-gateway/_meta/manifest.yml
- SentinelOne/cloud_funnel2.0/CHANGELOG.md
- SentinelOne/cloud_funnel2.0/_meta/smart-descriptions.json
- SentinelOne/cloud_funnel2.0/ingest/parser.yml
- SentinelOne/cloud_funnel2.0/tests/linux_process_processcreation.json
- SentinelOne/cloud_funnel2.0/tests/process_processcreation.json
Change the way to handle process creation events: move target information into process fields
> Sentinel: Change the way to operate process creation events

- SekoiaIO/endpoint/_meta/smart-descriptions.json
The objective is to improve the display of certain events upon deploying the agent on macOS.
> Add smart descriptions for certain events without command line

- Palo Alto Networks/paloalto-cortex-xdr/CHANGELOG.md
- Palo Alto Networks/paloalto-cortex-xdr/_meta/manifest.yml
> Change parser name

- HarfangLab/harfanglab/_meta/fields.yml
- HarfangLab/harfanglab/ingest/parser.yml
- HarfangLab/harfanglab/tests/network.json
- HarfangLab/harfanglab/tests/network2.json
Adding the direction field on network event
> Add direction field to harfanglab parser

- utils/show_smart_descriptions.py
Fix to support test paths with spaces
> Fix smart descriptions tool

- SpamAssassin/spamassassin/CHANGELOG.md
- SpamAssassin/spamassassin/_meta/fields.yml
- SpamAssassin/spamassassin/ingest/parser.yml
- SpamAssassin/spamassassin/tests/dns.json
- SpamAssassin/spamassassin/tests/processing.json
- SpamAssassin/spamassassin/tests/result.json
> feat(spamd): migrate code

- .github/workflows/main.yml
- utils/checks/__main__.py
Adds `--change` argument to check only the changed formats (as in `test_formats.py`)
> Improve format validator

- Fortinet/fortigate/_meta/fields.yml
- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/DNS.STANDARD.json
- Fortinet/fortigate/tests/DNS2.STANDARD.json
- Fortinet/fortigate/tests/WAD.STANDARD.json
- Fortinet/fortigate/tests/dns.CSV.json
- Fortinet/fortigate/tests/hostname.STANDARD.json
- Fortinet/fortigate/tests/icmp.json
- Fortinet/fortigate/tests/icmp6.json
- Fortinet/fortigate/tests/ping.json
- Fortinet/fortigate/tests/test_ips.STANDARD.json
- Fortinet/fortigate/tests/test_unauthuser.json
- Fortinet/fortigate/tests/traffic_forward.CSV.json
- Fortinet/fortigate/tests/traffic_forward.STANDARD.json
- Fortinet/fortigate/tests/traffic_forward.STANDARD_2.json
- Fortinet/fortigate/tests/traffic_nat.STANDARD.json
context: https://github.com/SekoiaLab/platform/issues/54441
> add parsing field policyid and poluuid

- WatchGuard/watchguard-firebox/_meta/smart-descriptions.json
- WatchGuard/watchguard-firebox/ingest/parser.yml
- WatchGuard/watchguard-firebox/tests/auth_was_rejected.json
- WatchGuard/watchguard-firebox/tests/user_auth_was_accepted.json
- WatchGuard/watchguard-firebox/tests/user_login_rejected.json
- WatchGuard/watchguard-firebox/tests/user_login_rejected_2.json
Fix the category and the type of rejected authentication messages.
> fWatchGuard: fix the categorization of the authentication messages

- Azure/azure-network-watcher/ingest/parser.yml
When the property flow_state is not available, set action.properties.flow_state and network.direction from the content of the flow
> Azure: Improve flow state

- Apache/apache/_meta/smart-descriptions.json
- Apache/apache/ingest/parser.yml
- Apache/apache/tests/access_combined.json
- Apache/apache/tests/common_log_format.json
- Apache/apache/tests/error.json
- Apache/apache/tests/error_2.json
- Apache/apache/tests/error_module.json
- Apache/apache/tests/modsecurity.json
- Apache/apache/tests/needs_striping.json
- Apache/apache/tests/process_id.json
Improve the support for error logs in module
> Apache: fix the way to parse error module logs

- AWS/aws-guardduty/_meta/manifest.yml
- AWS/aws-waf/_meta/manifest.yml
- Azure/azure-ad/_meta/manifest.yml
- Azure/azure-files/_meta/manifest.yml
- Azure/azure-front-door/_meta/manifest.yml
- Azure/azure-mysql/_meta/manifest.yml
- Azure/azure-windows/_meta/manifest.yml
- CybeReason/malop-json/_meta/manifest.yml
- Google Cloud/Google Kubernetes Engine/_meta/manifest.yml
- Google Cloud/Google VPC Flow Logs/_meta/manifest.yml
- Microsoft/microsoft-365-defender/_meta/manifest.yml
- Microsoft/microsoft-intune/_meta/manifest.yml
- Ubika/ubika-cloud-protector-alerts/_meta/manifest.yml
Link formats with automation connectors for integrations that use a connector.
- AWS formats linked with [aws_s3_logs](https://github.com/SEKOIA-IO/automation-library/blob/main/AWS/connector_s3_logs.json) connector
- Microsoft and Azure formats with [Azure EventHub connector](https://github.com/SEKOIA-IO/automation-library/blob/main/Azure/connector_azure_eventhub.json)
- Google formats with [Google Pubsub connectors](https://github.com/SEKOIA-IO/automation-library/blob/main/Google/connector_pubsub_query.json)
- Cybereason format with the new [cybereason connector](https://github.com/SEKOIA-IO/automation-library/blob/main/Cybereason/connector_pull_events_new.json)
- Ubika Cloud protector alerts format with [its connector](https://github.com/SEKOIA-IO/automation-library/blob/main/Ubika/conne …
> Add connectors information

- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/Configuration_changed.CEF.json
- Fortinet/fortigate/tests/ROLL-LOG.STANDARD.json
- Fortinet/fortigate/tests/ssh_access.CEF.json
- Fortinet/fortigate/tests/ssl_new_con.CEF.json
- Fortinet/fortigate/tests/vpn.STANDARD.json
- Fortinet/fortigate/tests/vpn_login_failed.STANDARD.json
- Fortinet/fortigate/tests/vpn_na_ip.STANDARD.json
change `final.<key>` that never returns None
> fix(fortigate): fix condition not working as expected

- Microsoft/microsoft-365-defender/ingest/parser.yml
- Microsoft/microsoft-365-defender/tests/test_device_network_events.json
fix https://github.com/SekoiaLab/platform/issues/55899
> fix typo in parser

- Azure/azure-key-vault/_meta/manifest.yml
- SentinelOne/cloud_funnel2.0/_meta/manifest.yml
Add automation information for Azure Key Vault and SentinelOne CloudFunnel 2.0
> Add automation information for formats that are missing it

- SentinelOne/cloud_funnel2.0/_meta/fields.yml
- SentinelOne/cloud_funnel2.0/ingest/parser.yml
- SentinelOne/cloud_funnel2.0/tests/commandscript.json
- SentinelOne/cloud_funnel2.0/tests/dns_dnsresolved.json
- SentinelOne/cloud_funnel2.0/tests/driver_driverload.json
- SentinelOne/cloud_funnel2.0/tests/file_filecreation_noext.json
- SentinelOne/cloud_funnel2.0/tests/file_filedeletion.json
- SentinelOne/cloud_funnel2.0/tests/file_filerename.json
- SentinelOne/cloud_funnel2.0/tests/group_groupcreation.json
- SentinelOne/cloud_funnel2.0/tests/indicators_behavioralindicators.json
- SentinelOne/cloud_funnel2.0/tests/ip_ipconnect.json
- SentinelOne/cloud_funnel2.0/tests/ip_ipconnect_incoming.json
- SentinelOne/cloud_funnel2.0/tests/ip_ipconnect_unsigned_process.json
- SentinelOne/cloud_funnel2.0/tests/linux_logins_login.json
- SentinelOne/cloud_funnel2.0/tests/linux_logins_logout.json
- SentinelOne/cloud_funnel2.0/tests/linux_process_processcreation.json
- SentinelOne/cloud_funnel2.0/tests/logins_login_failure.json
- SentinelOne/cloud_funnel2.0/tests/logins_login_success.json
- SentinelOne/cloud_funnel2.0/tests/process_processcreation.json
- SentinelOne/cloud_funnel2.0/tests/registry_binary.json
- SentinelOne/cloud_funnel2.0/tests/registry_keycreated.json
- SentinelOne/cloud_funnel2.0/tests/registry_security.json
- SentinelOne/cloud_funnel2.0/tests/registry_valuemodified.json
- SentinelOne/cloud_funnel2.0/tests/scheduledtask_taskregister.json
- SentinelOne/cloud_funnel2.0/tests/scheduledtask_taskstart.json
- SentinelOne/cloud_funnel2.0/tests/url.json
Add (back) storyline_id fields
> SentinelOne: add storyline_id fields

- Windows/windows/ingest/parser.yml
- Windows/windows/tests/registry.json
- Windows/windows/tests/sysmon_13_dword.json
- Windows/windows/tests/sysmon_13_strings.json
Fix linked to [this issue](https://github.com/SekoiaLab/integration/issues/16)
> Fix on registry.key for Windows

- SentinelOne/sentinelone/_meta/fields.yml
- SentinelOne/sentinelone/ingest/parser.yml
- SentinelOne/sentinelone/tests/activity-type-5126.json
> SentinelOne: remove vendorId custom field

- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/editpolicy.json
context: https://github.com/SekoiaLab/integration/issues/150
> parse pol uuid

- F5 Networks/f5-big-ip/_meta/smart-descriptions.json
- F5 Networks/f5-big-ip/ingest/parser.yml
- F5 Networks/f5-big-ip/tests/test_asm1.json
- F5 Networks/f5-big-ip/tests/test_audit.json
- F5 Networks/f5-big-ip/tests/test_cron.json
- F5 Networks/f5-big-ip/tests/test_logger2.json
- F5 Networks/f5-big-ip/tests/test_logger3.json
- F5 Networks/f5-big-ip/tests/test_sshd.json
- reorganize the grok patterns
- add support for audit messages
- add support for ssh messages
- improve parsing of logger messages
- fix support for CEF messages
> F5: Improve the F5 Big IP parser

- Varonis/varonis-data-security/ingest/parser.yml
https://github.com/SekoiaLab/integration/issues/173
> add 0 to severity

- SekoiaIO/endpoint/CHANGELOG.md
- SekoiaIO/endpoint/_meta/fields.yml
Parent task: [#59127](https://github.com/SekoiaLab/platform/issues/59127)
> Add time_without_events field to Agent

- Checkpoint/checkpoint/ingest/parser.yml
- Checkpoint/checkpoint/tests/CEF_proxy_src.json
https://github.com/SekoiaLab/integration/issues/162
> Fix Checkpoint format

- Microsoft/microsoft-365-defender/_meta/smart-descriptions.json
- Microsoft/microsoft-365-defender/tests/test_device_process_created.json
https://github.com/SekoiaLab/integration/issues/158
> M365D - Add smart description

- Postfix/postfix/ingest/parser.yml
- Postfix/postfix/tests/local5.json
- Postfix/postfix/tests/smtp3.json
https://github.com/SekoiaLab/integration/issues/222
> Postfix: handle when log.syslog.appname is empty or equals to the dash

- NGINX/nginx/ingest/parser.yml
- NGINX/nginx/tests/extended.json
- NGINX/nginx/tests/extended_backslash.json
https://github.com/SekoiaLab/integration/issues/218
> Nginx: extract the forwarded ip

- Apache/apache/ingest/parser.yml
- Apache/apache/tests/access_failure.json
- Apache/apache/tests/access_redirect.json
- Apache/apache/tests/access_success.json
Fix related to [this issue](https://github.com/SekoiaLab/integration/issues/240)
> fix on Apache parser for additional "-" in the logs

- Cisco/cisco-meraki/ingest/parser.yml
- Cisco/cisco-meraki/tests/test_flows_with_mac.json
https://github.com/SekoiaLab/integration/issues/242
> Cisco Meraki MX - parse MAC address

- NGINX/nginx/ingest/parser.yml
- NGINX/nginx/tests/json_get.json
Fix concerning [this issue](https://github.com/SekoiaLab/integration/issues/241)
> fix on NGINX: allowing conversion of string to int on action.outcome

- F5 Networks/f5-big-ip/_meta/fields.yml
- F5 Networks/f5-big-ip/_meta/smart-descriptions.json
- F5 Networks/f5-big-ip/ingest/parser.yml
- F5 Networks/f5-big-ip/tests/test_apm_access_1.json
- F5 Networks/f5-big-ip/tests/test_apm_access_2.json
- F5 Networks/f5-big-ip/tests/test_apm_access_3.json
- F5 Networks/f5-big-ip/tests/test_apm_access_4.json
- Wallix/wallix-bastion/tests/session_integrity.json
Closes [234](https://github.com/SekoiaLab/integration/issues/234)
> Fix: F5 Big Ip APM events support

- Windows/windows/ingest/parser.yml
- Windows/windows/tests/process_8002.json
- Windows/windows/tests/process_8005.json
Fix concerning [this issue](https://github.com/SekoiaLab/integration/issues/252)
> Addition of files fields for events 8002 and 8005

- Office 365/o365/ingest/parser.yml
- Office 365/o365/tests/security_compliance_alert_7.json
- Office 365/o365/tests/security_compliance_alert_malicious_url.json
To improve IOC matching and help with investigations.
> o365: Add parsing of URL for two types of SecurityComplianceAlerts

- Darktrace/darktrace-threat-visualizer/ingest/parser.yml
- Darktrace/darktrace-threat-visualizer/tests/test_aianalyst_2.json
- Darktrace/darktrace-threat-visualizer/tests/test_aianalyst_without_log_type.json
- Darktrace/darktrace-threat-visualizer/tests/test_anomalous_file.json
- Darktrace/darktrace-threat-visualizer/tests/test_device_attack_and_recon_tools.json
- Darktrace/darktrace-threat-visualizer/tests/test_device_request_watched_domain.json
https://github.com/SekoiaLab/integration/issues/271
> Fix Darktrace parser

- Salesforce/salesforce-events/ingest/parser.yml
- Salesforce/salesforce-events/tests/salesforce_complete_event.json
- Salesforce/salesforce-events/tests/salesforce_complete_event_1.json
- Salesforce/salesforce-events/tests/salesforce_login_event.json
- Salesforce/salesforce-events/tests/salesforce_login_event_1.json
- Wallix/wallix-bastion/tests/session_integrity.json
Closes [277](https://github.com/SekoiaLab/integration/issues/277)
> Fix: salesforce login event (277)

- HarfangLab/harfanglab/ingest/parser.yml
- HarfangLab/harfanglab/tests/authentication_2.json
https://github.com/SekoiaLab/integration/issues/275
> HarfangLab - fix ip parsing

- CrowdStrike/crowdstrike-telemetry/_meta/fields.yml
- CrowdStrike/crowdstrike-telemetry/ingest/parser.yml
- CrowdStrike/crowdstrike-telemetry/tests/telemetry_event_26.json
https://github.com/SekoiaLab/integration/issues/276
> CrowdStrike Telemetry - parse ContextBaseFileName

- VadeSecure/vade_secure_m365/_meta/fields.yml
- VadeSecure/vade_secure_m365/ingest/parser.yml
- VadeSecure/vade_secure_m365/tests/email_02.json
- VadeSecure/vade_secure_m365/tests/email_with_attachment_02.json
Improvement concerning [this issue](https://github.com/SekoiaLab/integration/issues/262)
> Improvement: Vade Secure M365 - Add parsed fields

- Microsoft/microsoft-365-defender/_meta/smart-descriptions.json
- Microsoft/microsoft-365-defender/tests/test_cloud_app4.json
- Microsoft/microsoft-365-defender/tests/test_device_logon_failed.json
- Microsoft/microsoft-365-defender/tests/test_email_delivered.json
- Microsoft/microsoft-365-defender/tests/test_email_delivered2.json
Fix concerning [this](https://github.com/SekoiaLab/integration/issues/290) and [this](https://github.com/SekoiaLab/integration/issues/245) issues
> Microsoft 365 defender : fix on smart descriptions

- HarfangLab/harfanglab/CHANGELOG.md
- HarfangLab/harfanglab/ingest/parser.yml
- HarfangLab/harfanglab/tests/alert.json
- HarfangLab/harfanglab/tests/alert_1.json
- HarfangLab/harfanglab/tests/alert_2.json
- HarfangLab/harfanglab/tests/alert_3.json
- HarfangLab/harfanglab/tests/alert_4.json
- HarfangLab/harfanglab/tests/alert_false_positive.json
- HarfangLab/harfanglab/tests/authentication.json
- HarfangLab/harfanglab/tests/dns.json
- HarfangLab/harfanglab/tests/network.json
- HarfangLab/harfanglab/tests/network2.json
- HarfangLab/harfanglab/tests/process-event.json
- HarfangLab/harfanglab/tests/process.json
- HarfangLab/harfanglab/tests/process2.json
- HarfangLab/harfanglab/tests/process3.json
- HarfangLab/harfanglab/tests/process4.json
https://github.com/SekoiaLab/integration/issues/323
> Harfanglab - normalize `user.name`

- HarfangLab/harfanglab/_meta/fields.yml
- HarfangLab/harfanglab/ingest/parser.yml
- HarfangLab/harfanglab/tests/alert_1.json
- HarfangLab/harfanglab/tests/alert_2.json
- HarfangLab/harfanglab/tests/alert_3.json
- HarfangLab/harfanglab/tests/alert_4.json
- HarfangLab/harfanglab/tests/alert_5.json
Fix concerning [this issue](https://github.com/SekoiaLab/integration/issues/325)
> HarfangLab: Adding field for Harfanglab Threat Key

- HarfangLab/harfanglab/_meta/fields.yml
- HarfangLab/harfanglab/ingest/parser.yml
- HarfangLab/harfanglab/tests/process-event.json
- HarfangLab/harfanglab/tests/process.json
- HarfangLab/harfanglab/tests/process3.json
- HarfangLab/harfanglab/tests/process4.json
Fix related to [this issue](https://github.com/SekoiaLab/integration/issues/330)
> HarfangLab: fix on process field

- HarfangLab/harfanglab/_meta/fields.yml
- HarfangLab/harfanglab/ingest/parser.yml
- HarfangLab/harfanglab/tests/process-event.json
- HarfangLab/harfanglab/tests/process4.json
Fix related to [this issue](https://github.com/SekoiaLab/integration/issues/330)
> HarfangLab: Fix on grandparents command line

- Bitdefender/gravityzone/_meta/manifest.yml
- GateWatcher/aioniq_ecs/_meta/manifest.yml
- Palo Alto Networks/paloalto-prisma-access/_meta/manifest.yml
Add the missing identifiers of the automation module related to the formats
> Formats: add automation modules

- Bitdefender/gravityzone/_meta/fields.yml
- Bitdefender/gravityzone/ingest/parser.yml
- Bitdefender/gravityzone/tests/login_1.json
- Bitdefender/gravityzone/tests/uc_event.json
Improvement concerning [this issue](https://github.com/SekoiaLab/integration/issues/331)
> Bitdefender : enhanced parser for uc events

- Fortinet/fortigate/_meta/smart-descriptions.json
- Fortinet/fortigate/ingest/parser.yml
- Fortinet/fortigate/tests/test_group_field.json
- Fortinet/fortigate/tests/test_group_field_1.json
- Fortinet/fortigate/tests/tunnel.json
Main issue : [Issue](https://github.com/SekoiaLab/integration/issues/346)
> Add group field with a smart desc

- EfficientIP/solidserver-ddi/_meta/fields.yml
- EfficientIP/solidserver-ddi/_meta/smart-descriptions.json
- EfficientIP/solidserver-ddi/ingest/parser.yml
- EfficientIP/solidserver-ddi/tests/dhcp_ack_01.json
- EfficientIP/solidserver-ddi/tests/dhcp_ack_02.json
- EfficientIP/solidserver-ddi/tests/dhcp_ack_03.json
- EfficientIP/solidserver-ddi/tests/dhcp_discover_01.json
- EfficientIP/solidserver-ddi/tests/dhcp_discover_02.json
- EfficientIP/solidserver-ddi/tests/dhcp_discover_03.json
- EfficientIP/solidserver-ddi/tests/dhcp_discover_04.json
- EfficientIP/solidserver-ddi/tests/dhcp_discover_05.json
- EfficientIP/solidserver-ddi/tests/dhcp_inform.json
- EfficientIP/solidserver-ddi/tests/dhcp_nack.json
- EfficientIP/solidserver-ddi/tests/dhcp_offer_01.json
- EfficientIP/solidserver-ddi/tests/dhcp_offer_02.json
- EfficientIP/solidserver-ddi/tests/dhcp_release_01.json
- EfficientIP/solidserver-ddi/tests/dhcp_release_02.json
- EfficientIP/solidserver-ddi/tests/dhcp_request_01.json
- EfficientIP/solidserver-ddi/tests/dhcp_request_02.json
- EfficientIP/solidserver-ddi/tests/dhcp_request_03.json
Improvement concerning [this issue](https://github.com/SekoiaLab/integration/issues/319)
> Efficient IP: Add DHCP message types

- Google Cloud/google-report/_meta/manifest.yml
https://github.com/SekoiaLab/platform/issues/63769
> typo(google_cloud) Correct spelling errors in Google Report description

- HarfangLab/harfanglab/_meta/fields.yml
- HarfangLab/harfanglab/ingest/parser.yml
- HarfangLab/harfanglab/tests/test_threat_log_1.json
- HarfangLab/harfanglab/tests/threat_critical.json
- HarfangLab/harfanglab/tests/threat_log.json
Main Issue : [issue](https://github.com/SekoiaLab/integration/issues/344)
> Add some other fields to harfanglab

- Office 365/o365/ingest/parser.yml
- Office 365/o365/tests/test_appName_field.json
Main issue : [Issue](https://github.com/SekoiaLab/integration/issues/350)
> Add app name field

- Netskope/netskope_events/_meta/smart-descriptions.json
- Netskope/netskope_events/tests/test_dlp_incident_wo_policy.json
https://github.com/SekoiaLab/integration/issues/353
> Netskope - add more smart descriptions

- Umbrella/umbrella-dns/_meta/fields.yml
- Umbrella/umbrella-dns/ingest/parser.yml
- Umbrella/umbrella-dns/tests/DNS_Tunnel.json
- Umbrella/umbrella-dns/tests/umbrella-dns-1.json
- Umbrella/umbrella-dns/tests/umbrella-dns-2.json
- Umbrella/umbrella-dns/tests/umbrella-dns-3.json
- Umbrella/umbrella-dns/tests/umbrella-dns-5.json
- Umbrella/umbrella-dns/tests/umbrella-dns-6.json
- Umbrella/umbrella-dns/tests/umbrella-dns-7.json
- Umbrella/umbrella-dns/tests/umbrella-dns-8.json
[New fields](https://github.com/SekoiaLab/integration/issues/359#issuecomment-2596137871) for Umbrella DNS parser
> Umbrella DNS: addition of new fields

- Cisco/cisco-secure-firewall/ingest/parser.yml
- Cisco/cisco-secure-firewall/tests/test_FTD_750003.json
Fix related to [this issue](https://github.com/SekoiaLab/integration/issues/372)
> Cisco Firewall: Addition of Grok for event 750003

- Zscaler/zscaler-zia/_meta/fields.yml
- Zscaler/zscaler-zia/ingest/parser.yml
- Zscaler/zscaler-zia/tests/test_event_dns.json
- Zscaler/zscaler-zia/tests/test_event_web.json
- Zscaler/zscaler-zia/tests/test_event_web2.json
- Zscaler/zscaler-zia/tests/test_event_web3.json
- Zscaler/zscaler-zia/tests/test_tunnel_gre.json
- Zscaler/zscaler-zia/tests/test_tunnel_ipsev_ikev1.json
- Zscaler/zscaler-zia/tests/test_tunnel_ipsev_ikev2.json
https://github.com/SekoiaLab/integration/issues/374
> ZScaler - Parse more fields

- Netskope/netskope_events/_meta/smart-descriptions.json
Add smart descriptions for Netskope application authentication events
> [Netskope Events] New smart descriptions

- Google Cloud/google-report/_meta/manifest.yml
Main issue : [Issue](https://github.com/SekoiaLab/integration/issues/391)
> Change the name of the parser

- BeyondTrust/beyondtrust-pra/_meta/smart-descriptions.json
Add additional smart-descriptions with more details in the description.
> BeyondTrust: add more smart-descriptions

- OpenBSD/openbsd-packet-filter/_meta/fields.yml
- OpenBSD/openbsd-packet-filter/_meta/smart-descriptions.json
- OpenBSD/openbsd-packet-filter/ingest/parser.yml
- OpenBSD/openbsd-packet-filter/tests/test_icmp_request_01.json
- OpenBSD/openbsd-packet-filter/tests/test_icmp_request_02.json
- OpenBSD/openbsd-packet-filter/tests/test_icmp_request_03.json
- OpenBSD/openbsd-packet-filter/tests/test_icmp_request_04.json
- OpenBSD/openbsd-packet-filter/tests/test_icmp_unreach_01.json
- OpenBSD/openbsd-packet-filter/tests/test_icmp_unreach_02.json
- OpenBSD/openbsd-packet-filter/tests/test_icmp_unreach_03.json
Fix related to [this issue](https://github.com/SekoiaLab/integration/issues/410)
> OpenBSD: fix for ICMP parsing

- Cisco/cisco-secure-firewall/ingest/parser.yml
- Cisco/cisco-secure-firewall/tests/test_FTD_722051_1.json
- Cisco/cisco-secure-firewall/tests/test_FTD_722051_2.json
https://github.com/SekoiaLab/integration/issues/408
> Cisco Secure Firewall - add FTD-722051 events

- Okta/okta-system-logs/ingest/parser.yml
- Okta/okta-system-logs/tests/test_authentication_sso_with_slashes.json
https://github.com/SekoiaLab/integration/issues/422
> Okta - remove double slashes from email

- Office 365/o365/_meta/smart-descriptions.json
- Office 365/o365/tests/security_compliance_alert_8.json
https://github.com/SekoiaLab/integration/issues/415
> O365 - fix smart descriptions

- SentinelOne/sentinelone/_meta/smart-descriptions.json
- SentinelOne/sentinelone/tests/activity-type-5126-2.json
https://github.com/SekoiaLab/integration/issues/415
> SentinelOne - fix smart descriptions

- SesameIT/_meta/manifest.yml
- SesameIT/jizo/_meta/manifest.yml
> SesameIT: rename the format and the module

- VMWare/vmware-esxi/ingest/parser.yml
Revert this fix as it generate a lot of questions
> ESXi fix : display warnings on unfit logs

- AWS/aws-flow-logs/_meta/fields.yml
- AWS/aws-flow-logs/ingest/parser.yml
- AWS/aws-flow-logs/tests/accept_ok_v5.json
- AWS/aws-flow-logs/tests/custom.json
- AWS/aws-flow-logs/tests/network_traffic.json
https://github.com/SekoiaLab/integration/issues/429
> AWS flog logs - parse tcp flags

- Palo Alto Networks/paloalto-ngfw/ingest/parser.yml
- Palo Alto Networks/paloalto-ngfw/tests/hash_in_filename.json
https://github.com/SekoiaLab/integration/issues/793
> PaloAlto NGFW - process hashes in filename field
