SEKOIA-IO/intake-formats

Squid/squid/ingest/parser.yml
Squid/squid/tests/connect_ip.json

In the previous implementation, in some situations we pushed IPs in the `destination.domain` field.

fix(squid): Fill `destination.ip` if we are facing an IP

---

.github/workflows/trigger-documentation-rebuild.yaml

Use [`getsentry/action-github-app-token@v1`](https://github.com/getsentry/action-github-app-token) action with a dedicated GitHub App to push a `repository_dispatch` event to the documentation repository when a the `master` branch is updated.
Dedicated application has limited rights to the https://github.com/SEKOIA-IO/documentation repository.
To work as expected, this requires https://github.com/SEKOIA-IO/documentation/pull/202 to be merged.

ci: Trigger a documentation rebuild on merged PR

---

Azure/azure-linux/ingest/parser.yml

Do not fail parsing if `properties.Msg` is missing

fix(azure-linux): fix failing when Msg field missing

---

Azure/azure-linux/ingest/parser.yml

Add some checks to not fail parsing when message doesn't contain `properties`

fix(azure-linux): fix missing properties check

---

Azure/azure-windows/ingest/parser.yml
Azure/azure-windows/tests/restart_manager.json

With the parser to not failed when handling windows Event with no EventData part

Azure: fix Azure windows parser with no EventData details

---

Cisco/cisco-wsa/ingest/parser.yml
Cisco/cisco-wsa/tests/event1.json
Cisco/cisco-wsa/tests/prefixed.json

Fix the parser to handle the prefix `Info: ` added in the payload of syslog message

Cisco: handle syslog prefixed payload

---

utils/new_intake/cookiecutter.json
utils/new_intake/{{cookiecutter.intake_slug}}/_meta/manifest.yaml
utils/new_intake/{{cookiecutter.intake_slug}}/ingest/parser.yml
utils/new_intake/{{intake_slug}}/_meta/manifest.yaml
utils/new_intake/{{intake_slug}}/ingest/parser.yml
utils/new_module/cookiecutter.json
utils/new_module/{{cookiecutter.module_dir}}/README.md
utils/new_module/{{cookiecutter.module_dir}}/_meta/manifest.yaml

Update `utils/new_module` and `utils/new_intake` to be compliant with cookie cutter

Utils: Make generation template compliant with cookiecutter

---

.github/workflows/test.yml
utils/conftest.py
utils/poetry.lock
utils/pyproject.toml
utils/test_formats.py

This PR introduces a script that can be used to validate intake formats:
* Verify expected outputs
* Compute test coverage
* Detect unused or missing fields
The script is automatically run on Pull Requests.
It requires a validation endpoint on ingestapi that is not yet deployed, so all tests will fail for now.

feat: intake format validation

---

Office 365/o365/_meta/fields.yml
Office 365/o365/tests/ad.json
Office 365/o365/tests/exchange_event1.json
Office 365/o365/tests/file_previewed.json
Office 365/o365/tests/file_sync_download_full.json
Office 365/o365/tests/teams_message_has_link.json
Office 365/o365/tests/update_group.json
Office 365/o365/tests/update_user.json
Office 365/o365/tests/update_user_empty_source_ip.json
Office 365/o365/tests/user_logged_in.json

Fix Office365 field types. Some object fields were previously declared as text fields, which was incompatible with the future version of ingest.
Tests will not pass until the new version of ingest is deployed, but we need this update to deploy the new version 😅

fix(o365): fix field types

---

Beats/auditbeat/_meta/fields.yml

Fix the `system.audit.user.group` field type that is [actually an object](https://www.elastic.co/guide/en/beats/auditbeat/current/exported-fields-system.html)

fix(audibeat): user group field is an object

---

SekoiaIO/endpoint/_meta/fields.yml
SekoiaIO/endpoint/tests/windows_defender.json

Make sure that any field that is inside `action.properties` and not listed in the fields is still added to the event, without errors.
Unfortunately, this also means that declared fields inside `action.properties` no longer have their type enforced.

fix(sekoiaio_endpoints): consider action.properties as an opaque object

---

Office 365/o365/ingest/parser.yml
Office 365/o365/tests/teams_message_has_link.json

Remove the extraction of url.original for teams links to avoid misinterpretation

Office365: remove the extract of url.original from teams links

---

SentinelOne/sentinelone/ingest/parser.yml

SentinelOne: only parse defined dates

---

Microsoft Defender/microsoft-defender-for-endpoints/ingest/parser.yml
Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_event.json
Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_file_event.json
Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_image_load_event.json
Microsoft Defender/microsoft-defender-for-endpoints/tests/test_local_ip.json

Use the filter `dirname` to only get the path to the working directory, as the original field contains the executable.

MDForEndpoint: fix the working directory for a process

---

Fortinet/fortigate/ingest/parser.yml
Fortinet/fortigate/tests/Configuration_changed.CEF.json
Fortinet/fortigate/tests/IP_SEC.STANDARD.json
Fortinet/fortigate/tests/LOGOUT.STANDARD.json
Fortinet/fortigate/tests/ROLL-LOG.STANDARD.json
Fortinet/fortigate/tests/WAD.STANDARD.json
Fortinet/fortigate/tests/dns.CSV.json
Fortinet/fortigate/tests/hostname.STANDARD.json
Fortinet/fortigate/tests/icmp.json
Fortinet/fortigate/tests/icmp6.json
Fortinet/fortigate/tests/icmp_CEF.json
Fortinet/fortigate/tests/ping.json
Fortinet/fortigate/tests/ssh_access.CEF.json
Fortinet/fortigate/tests/ssl_new_con.CEF.json
Fortinet/fortigate/tests/traffic_forward.CEF-Axens.json
Fortinet/fortigate/tests/traffic_forward.CSV.json
Fortinet/fortigate/tests/traffic_forward.STANDARD.json
Fortinet/fortigate/tests/traffic_forward.STANDARD_STET.json
Fortinet/fortigate/tests/traffic_forward_FTNTFGTtz.CEF.json
Fortinet/fortigate/tests/traffic_nat.STANDARD.json
Fortinet/fortigate/tests/tunnel.json
Fortinet/fortigate/tests/tunnel_statistics.CSV.json
Fortinet/fortigate/tests/vpn.STANDARD.json

This is a fix to [#28115](https://github.com/SekoiaLab/platform/issues/28115)

Add timestamp fields respecting ECS format to event

---

AWS/aws-cloudtrail/_meta/fields.yml
AWS/aws-cloudtrail/_meta/smart-descriptions.json

Use the ARN instead of the account ID in smart-description

AWS: fix smart-descriptions

---

Broadcom/symantec-endpoint-protection/_meta/smart-descriptions.json
Broadcom/symantec-endpoint-protection/ingest/parser.yml
Broadcom/symantec-endpoint-protection/tests/test_behavior_logs.json

Update parser with last modification
fix `process.args`: don't split the content as the parameters are in one piece.

Symantec EPP: fix parser

---

Fortinet/fortigate/ingest/parser.yml
Fortinet/fortigate/tests/traffic_forward-RDP.CEF.json

extract DeviceEventClassId from the CEF message to value `event.code`

Fortinet: extract DeviceEventClassId from the CEF message

---

Fortinet/fortigate/_meta/smart-descriptions.json
Fortinet/fortigate/ingest/parser.yml
Fortinet/fortigate/tests/Configuration_changed.CEF.json
Fortinet/fortigate/tests/DLP.CEF.json
Fortinet/fortigate/tests/DNS.CEF.json
Fortinet/fortigate/tests/IPS.CEF.json
Fortinet/fortigate/tests/SSH.CEF-2.json
Fortinet/fortigate/tests/VoIP.CEF.json
Fortinet/fortigate/tests/WAF.CEF.json
Fortinet/fortigate/tests/anomaly.CEF-2.json
Fortinet/fortigate/tests/anomaly.CEF.json
Fortinet/fortigate/tests/antivirus.CEF-2.json
Fortinet/fortigate/tests/antivirus.CEF.json
Fortinet/fortigate/tests/application.CEF.json
Fortinet/fortigate/tests/email-spamfilter.CEF.json
Fortinet/fortigate/tests/event_log_system_subtype.CEF.json
Fortinet/fortigate/tests/event_log_user_subtype.CEF.json
Fortinet/fortigate/tests/icmp_CEF.json
Fortinet/fortigate/tests/ssh_access.CEF.json
Fortinet/fortigate/tests/ssl_new_con.CEF.json
Fortinet/fortigate/tests/traffic_forward-RDP.CEF.json
Fortinet/fortigate/tests/traffic_forward.CEF-2.json
Fortinet/fortigate/tests/traffic_forward.CEF-3.json
Fortinet/fortigate/tests/traffic_forward.CEF.json
Fortinet/fortigate/tests/traffic_forward_FTNTFGTtz.CEF.json
Fortinet/fortigate/tests/webfilter.CEF.json

- Remove `event.severity` to avoid indexing issue
- Extract FTNTFGTseverity from events
- Fix smart-description

Fortigate: fix severity

---

Fortinet/fortigate/ingest/parser.yml
Fortinet/fortigate/tests/DLP.CEF.json
Fortinet/fortigate/tests/IPS.CEF.json
Fortinet/fortigate/tests/application.CEF.json
Fortinet/fortigate/tests/hostname.STANDARD.json
Fortinet/fortigate/tests/webfilter.CEF.json

add a condition to only fill url.full when url.original starts with http
Copy the behavior define in the logstash parser.

Fortigate: fill url.full when url.original starts with http

---

Fortinet/fortigate/ingest/parser.yml
Fortinet/fortigate/tests/Configuration_changed.CEF.json
Fortinet/fortigate/tests/DNS.STANDARD.json
Fortinet/fortigate/tests/DNS2.STANDARD.json
Fortinet/fortigate/tests/icmp.json
Fortinet/fortigate/tests/icmp6.json
Fortinet/fortigate/tests/ping.json
Fortinet/fortigate/tests/test_unauthuser.json
Fortinet/fortigate/tests/traffic_forward_FTNTFGTtz.CEF.json
Fortinet/fortigate/tests/tunnel.json
Fortinet/fortigate/tests/vpn_login_failed.STANDARD.json
Fortinet/fortigate/tests/vpn_na_ip.STANDARD.json

Remove the usage of timezone when parsing timestamp

Fortinet: fix date parsing

---

utils/conftest.py

- Handle when fields.yml exists but it's empty
- Display the response of Ingest when the format is invalid

Utils: add some fix for tests

---

CrowdStrike/crowdstrike_falcon/ingest/parser.yml
CrowdStrike/crowdstrike_falcon/tests/detection_summary_event.json

Some setters were referencing an improper stage name

Fix Crowdstrike parser

---

Okta/okta-system-logs/ingest/parser.yml

Look for the information about the user in the field `actor` first and then, if defined, look for this information in the field `target`.

Okta: change the way to define ECS  fields

---

Cloudflare/firewall_events/ingest/parser.yml
Cloudflare/http_requests/_meta/fields.yml

Cloudflare is currently migrating some fields in the datasets `http_request` and `firewall_events` according to [this announcement](https://developers.cloudflare.com/logs/reference/change-notices/2023-02-01-security-fields-updates/).
Add the new Security fields to handle them.

Cloudflare: add new Security fields

---

IBM/ibm-aix/ingest/parser.yml
IBM/ibm-aix/tests/FILE_Pipe.json

fix the grok pattern to allow whitespace at the beginning of the message.

IBM: handle when message start with whitespaces

---

Sophos/sophos firewall/_meta/smart-descriptions.json

fix typo that invalidated the smart-descriptions file as a json document

Sophos: fix typo

---

Beats/winlogbeat/_meta/fields.yml
Beats/winlogbeat/ingest/parser.yml
Beats/winlogbeat/tests/test_filtering.json
Beats/winlogbeat/tests/test_logon.json

rename winlog.event_data.* fields into action.properties.* in the winlogbeat format

Beats: add support for action.properties fields

---

WatchGuard/watchguard-firebox/ingest/parser.yml
WatchGuard/watchguard-firebox/tests/dpi_http_2.json

Handle when facing event without the prefix LEEF.

WatchGuard: handle when the LEEF prefix is missing

---

CEF/cef/tests/cisco_esa_cef.json

I removed the wrong value in tests files since:
- we have a dedicated format for Cisco
- the CEF format is not intended to be bullet proof against miss-usage of a field

fix(cef/tests): fix wrong value `str` for field type `float`

---

Cloudflare/gateway_network/ingest/parser.yml
Cloudflare/gateway_network/tests/test_network.json
Cloudflare/gateway_network/tests/test_network_no_sni.json

To make pivoting and IOC detection easier, this PR copies the SNI (`tls.client.server_name`) to `destination.domain` .
This is in line with the ECS specification:
> **tls.client.server_name:** Also called an SNI, [...]. When this value is available, it should get copied to `destination.domain`.
https://www.elastic.co/guide/en/ecs/current/ecs-tls.html#field-tls-client-server-name
Note: I explicitely force `destination.address` to be the same as `destination.ip` event if `destination.domain` is present because this seems more exact in this context (these logs are similar to firewall logs, not proxy logs).

fix(Cloudflare/gateway_network): set destination.domain if SNI present

---

utils/test_formats.py

Ignore sekoia.intake.parsing_duration_ms from tests

Tests: ignore sekoia.intake.parsing_duration_ms

---

Ubika/ubika_waap/CHANGELOG.md
Ubika/ubika_waap/_meta/smart-descriptions.json
Ubika/ubika_waap/ingest/parser.yml
Ubika/ubika_waap/tests/test_access_event.json
Ubika/ubika_waap/tests/test_bot_mitigation_event.json
Ubika/ubika_waap/tests/test_security_log_event.json
Ubika/ubika_waap/tests/test_wam_log_event.json

It seems that a colon can actually appear in a separator, but only for access log events. Improving parsing pattern to allow this.

Fix access logs events for Ubika

---

SentinelOne/cloud_funnel2.0/_meta/fields.yml
SentinelOne/cloud_funnel2.0/tests/commandscript.json
SentinelOne/cloud_funnel2.0/tests/dns_dnsresolved.json
SentinelOne/cloud_funnel2.0/tests/file_filedeletion.json
SentinelOne/cloud_funnel2.0/tests/group_groupcreation.json
SentinelOne/cloud_funnel2.0/tests/indicators_behavioralindicators.json
SentinelOne/cloud_funnel2.0/tests/linux_process_processcreation.json
SentinelOne/cloud_funnel2.0/tests/logins_login_failure.json
SentinelOne/cloud_funnel2.0/tests/logins_login_success.json
SentinelOne/cloud_funnel2.0/tests/process_processcreation.json
SentinelOne/cloud_funnel2.0/tests/registry_binary.json
SentinelOne/cloud_funnel2.0/tests/registry_security.json
SentinelOne/cloud_funnel2.0/tests/scheduledtask_taskregister.json
SentinelOne/cloud_funnel2.0/tests/scheduledtask_taskstart.json

Change back to `keyword` the type of boolean string in the taxonomy.

SentinelOne: revert fix on boolean string

---

Office 365/o365/_meta/fields.yml
Office 365/o365/ingest/parser.yml
Office 365/o365/tests/inbox_rule.json

I have closed #535 and will split it in several PRs.
The [_ExchangeAdmin_](https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#exchange-admin-schema) event type has a _Parameters_ field which is an array of Name-Value pairs, e.g.:
```json
"Parameters": [
{
"Name": "ForwardTo",
"Value": "bob@example.org"
},
{
"Name": "Force",
"Value": "False"
},
```
This PR parses and reformats this as
```json
"office365": {
"exchange_admin": {
"parameters": [
"ForwardTo:bob@example.org",
"RedirectTo:joe@example.org",
```
* The use of an `office365.exchange_admin` namespace mimics what already exists for instance with `office365.teams` and `office365.defender`.
* The array of `key:value` strings mimics what exists in some `sekoiaio.tags` fields. It's …

feat(Office 365): Parse ExchangeAdmin parameters

---

OpenBSD/openbsd-packet-filter/ingest/parser.yml
OpenBSD/openbsd-packet-filter/tests/test_ingest_ipv4_carp_logs.json

Change the GROK pattern for the interface because a customer could have an interface name like "interface.1" which was not working with a `DATA` GROK pattern.
Tests have been ran.

fix(pfilter): change grok pattern for interface

---

OpenBSD/openbsd-packet-filter/ingest/parser.yml

Handle the weird case where logs start with a space. I used the same technique than the `Forcepoint` Intake. (`"CEF:{{original.message.strip()}}")
Those spaces are present since with decided to remove log.original from the log. 
This update doesn't change anything for the test logs.

update(packet-filter): case where the log start with a space

---

Sophos/sophos-analysis-threat-center/ingest/parser.yml
Sophos/sophos-analysis-threat-center/tests/ioc_view_query3.json
Sophos/sophos-analysis-threat-center/tests/ioc_view_query4.json

- Use `user.target` to hold all information about the targeted user
- update tests according to the finalizer on `file`

Sophos: Fix User targeted

---

Windows/windows/ingest/parser.yml
Windows/windows/tests/wrong-startswith.json

Imports the patch from Logstash for syslog configurations which adds a `:` before the json

fix(windows): add missing patch for wrong char at the start of the json message

---

Sophos/sophos-analysis-threat-center/CHANGELOG.md
Sophos/sophos-analysis-threat-center/ingest/parser.yml

Handle when ml_score_data is an empty string

Sophos: fix the extraction of ml_score_data

---

Aruba Network/aruba-os/_meta/manifest.yml

add Switch to the name of the format

Aruba: fix the name

---

FreeRADIUS/freeradius/CHANGELOG.md
FreeRADIUS/freeradius/ingest/parser.yml
FreeRADIUS/freeradius/tests/test_invalid_user.json
FreeRADIUS/freeradius/tests/test_login_incorrect1.json
FreeRADIUS/freeradius/tests/test_login_incorrect2.json
FreeRADIUS/freeradius/tests/test_login_ok1.json
FreeRADIUS/freeradius/tests/test_login_ok2.json
FreeRADIUS/freeradius/tests/test_login_ok3.json
FreeRADIUS/freeradius/tests/test_login_ok4.json
FreeRADIUS/freeradius/tests/test_login_ok5.json
FreeRADIUS/freeradius/tests/test_login_ok6.json
FreeRADIUS/freeradius/tests/test_login_ok7.json
FreeRADIUS/freeradius/tests/test_login_ok8.json

move the value from `network.name` to `host.name` as the value represents the name of the host

Freeradius: move the value from network.name to host.name

---

utils/test_formats.py

The bug was messing up `fields.yml` by dumping yaml twice: in `prune_taxonomy` and in `write_taxonomy` functions

Fix field pruning

---

Microsoft/microsoft-365-defender/ingest/parser.yml
Microsoft/microsoft-365-defender/tests/test_device_event.json
Microsoft/microsoft-365-defender/tests/test_device_file_event.json
Microsoft/microsoft-365-defender/tests/test_device_image_load_event.json
Microsoft/microsoft-365-defender/tests/test_device_logon_events.json
Microsoft/microsoft-365-defender/tests/test_device_network_events.json
Microsoft/microsoft-365-defender/tests/test_device_process_events.json
Microsoft/microsoft-365-defender/tests/test_device_registry_events.json
Microsoft/microsoft-365-defender/tests/test_local_ip.json

Hi!
This PR adds the field `process.executable`, which we use for a lot of endpoint rules, but is currently not set in the M365 Defender format.

fix(Microsoft365Defender): add process.executable

---

Azure/azure-ad/_meta/fields.yml
Azure/azure-ad/ingest/parser.yml
Azure/azure-ad/tests/empty_geolocalisation.json
Azure/azure-ad/tests/sign-in_activity.json
Azure/azure-ad/tests/sign-in_activity2.json
Azure/azure-ad/tests/sign-in_activity3.json
Azure/azure-ad/tests/sign-in_activity4.json
Office 365/o365/ingest/parser.yml
Office 365/o365/tests/ad.json
Office 365/o365/tests/ad_1.json
Office 365/o365/tests/user_logged_in.json
Office 365/o365/tests/user_logged_in_2.json
Office 365/o365/tests/user_login_failed.json

Hi!
This is not a customer request, but I'd like to have these fields available to create detection rules.
On O365, I reused an existing field that has the same meaning in other events (it designates the client_id of an OAuth app).
On Azure AD, I created an new field with a name similar to the one that already exists for the app name.

Add OAuth client app ID (Azure AD, Office 365)

---

Office 365/o365/ingest/parser.yml
Office 365/o365/tests/exchange_event1.json
Office 365/o365/tests/exchange_item_update.json

Hi!
This is not a customer request, but I'd like to have these fields available to create detection rules.
I used existing ECS fields (`email.subject` and `email.message_id`).

Office365: Add subject and message_id in Exchange events

---

Squid/squid/_meta/smart-descriptions.json

A proposal to add a simple smart description for HTTP Connect method, commonly use for HTTPS through proxy.

feat(squid): adding simple HTTP connect smart desc

---

Azure/azure-network-watcher/ingest/parser.yml
Azure/azure-network-watcher/tests/continue.json
Azure/azure-network-watcher/tests/test_begin.json
Azure/azure-network-watcher/tests/test_end.json
Azure/azure-network-watcher/tests/test_short.json

`event.kind: "event"` is now considered as useless. I remove this field from the format

Azure: remove 'event.kind'

---

Olfeo/olfeo-secure-web-gateway/_meta/fields.yml
Olfeo/olfeo-secure-web-gateway/ingest/parser.yml
Olfeo/olfeo-secure-web-gateway/tests/network_log.json
Olfeo/olfeo-secure-web-gateway/tests/network_log_no_user.json
Olfeo/olfeo-secure-web-gateway/tests/network_log_space.json

The integer before the category of the URL is the category identifier.
Fix the parser in accordance

Olfeo: fix the category identifier

---

SentinelOne/cloud_funnel2.0/ingest/parser.yml
SentinelOne/cloud_funnel2.0/tests/dns_macos.json

Add support for dns events from Mac OS X that prefixes the `event.dns.request` value with the type of the request

SentinelOne: add support for dns events from Mac OS X

---

Azure/azure-ad/ingest/parser.yml

Fix missing `action.outcome` for SigninLogs by setting `action.outcome` from `properties.result` field only for AuditLogs events

Entra ID - Fix missing action.outcome for SigninLogs

---

Microsoft/microsoft-intune/ingest/parser.yml
Microsoft/microsoft-intune/tests/DeviceComplianceOrg.json

Review `host.name` field, actions to:
* add `DeviceHostName` info
* prioritize with the order `DeviceHostName` -> `DeviceName` -> `ManagedDeviceName`
That doe not solve issues with uuid, name + date concatenation.

fix(microsoft-intune): adding DeviceHostName and priority

---

Fortinet/fortigate/_meta/fields.yml
Fortinet/fortigate/ingest/parser.yml
Fortinet/fortigate/tests/DNS.STANDARD.json
Fortinet/fortigate/tests/DNS2.STANDARD.json
Fortinet/fortigate/tests/IP_SEC.STANDARD.json
Fortinet/fortigate/tests/LOGOUT.STANDARD.json
Fortinet/fortigate/tests/ROLL-LOG.STANDARD.json
Fortinet/fortigate/tests/WAD.STANDARD.json
Fortinet/fortigate/tests/editpolicy.json
Fortinet/fortigate/tests/event_logdev.json
Fortinet/fortigate/tests/forwadedfor.json
Fortinet/fortigate/tests/hostname.STANDARD.json
Fortinet/fortigate/tests/icmp.json
Fortinet/fortigate/tests/icmp6.json
Fortinet/fortigate/tests/ping.json
Fortinet/fortigate/tests/test_ips.STANDARD.json
Fortinet/fortigate/tests/traffic_forward.STANDARD_2.json
Fortinet/fortigate/tests/traffic_nat.STANDARD.json
Fortinet/fortigate/tests/tunnel.json
Fortinet/fortigate/tests/tunnel_statistics.CSV.json
Fortinet/fortigate/tests/vpn.STANDARD.json
Fortinet/fortigate/tests/vpn_login_failed.STANDARD.json
Fortinet/fortigate/tests/vpn_na_ip.STANDARD.json

Fix concerning [this issue](https://github.com/SekoiaLab/integration/issues/210).
Some tests have also been updated, probably from a previous fix (disappearance of host.name field, but the info is still present on log.hostname)

Fortigate: Addition of logdev fields in the parser

---

OCSF/ocsf/ingest/parser.yml
OCSF/ocsf/tests/test_dns_activity_3.json

Fix the parsing of the dns answers, from the raw events, when containing several answers.

OCSF: fix the parsing of dns answers

---

Apache/apache/ingest/parser.yml
Apache/apache/tests/access_combined.json
Apache/apache/tests/access_extended.json

- Add ignored values
- remove quotes from the user-agent and the HTTP referer
- extract the destination address that can prefix the log

Apache: Fix the parser

---

GateWatcher/aioniq/ingest/parser.yml
GateWatcher/aioniq/tests/sigflow-alert.json

The previous changes withdrawn the `event.kind` for alerts

Gatewatcher: add event.kind:alert when processing an alert

---

Office 365/o365/ingest/parser.yml
Office 365/o365/tests/microsoft_defender_threatintelligence_url_click.json

To improve IOC matching and help with investigations.

fix(o365): parse url in TIUrlClickData events

---

Office 365/o365/ingest/parser.yml
Office 365/o365/tests/clientipadress.json
Office 365/o365/tests/exchange_item_update.json
Office 365/o365/tests/inbox_rule.json

I'd like to use this field for a detection rule.

fix(o365): Parse ClientAppId in Exchange events

---

Palo Alto Networks/paloalto-ngfw/_meta/fields.yml
Palo Alto Networks/paloalto-ngfw/ingest/parser.yml
Palo Alto Networks/paloalto-ngfw/tests/system_csv.json
Palo Alto Networks/paloalto-ngfw/tests/test_event_reason2.json
Palo Alto Networks/paloalto-ngfw/tests/test_event_reason3.json
Palo Alto Networks/paloalto-ngfw/tests/test_system_event_13.json
Palo Alto Networks/paloalto-ngfw/tests/test_system_event_14.json

Fix concerning [this issue](https://github.com/SekoiaLab/integration/issues/334)
I also renamed a custom field containing a typo in its name

PaloAlto: fix for event auth-fail

---

Azure/azure-ad/_meta/fields.yml
Azure/azure-ad/ingest/parser.yml
Azure/azure-ad/tests/empty_geolocalisation.json
Azure/azure-ad/tests/sign-in_activity.json
Azure/azure-ad/tests/sign-in_activity2.json
Azure/azure-ad/tests/sign-in_activity3.json
Azure/azure-ad/tests/sign-in_activity4.json
Azure/azure-ad/tests/user_risk_detection.json
Azure/azure-ad/tests/user_risk_detection_2.json
Azure/azure-ad/tests/user_risk_detection_3.json

Fix related to [this issue](https://github.com/SekoiaLab/integration/issues/338)
As there is no standardization for the Level field for this format, I only stringified the field when it contains a number (using the Syslog standard might generate issues in some cases), so it might be quite poor in informations depending on the events, i.e. no idea of the meaning of the aforementioned level. Feel free to provide feedback if you have a better idea concerning the depiction of those fields.

Azure AD: change azuread.Level type from float to keyword

---

Office 365/o365/ingest/parser.yml
Office 365/o365/tests/automated_investigation_and_response_1.json
Office 365/o365/tests/automated_investigation_and_response_2.json
Office 365/o365/tests/automated_investigation_and_response_with_additional_fields.json
Office 365/o365/tests/automated_investigation_and_response_with_additional_fields_1.json
Office 365/o365/tests/automated_investigation_and_response_with_attachment.json
Palo Alto Networks/paloalto-prisma-access/_meta/manifest.yml

Refactor `office365.investigation.email.*` fields and `email.*` fields to remove empty arrays.

Office365: remove empty arrays

---

Office 365/o365/ingest/parser.yml
Office 365/o365/tests/user_login_failed.json

I wasn't able to neither find `event.outcome` in the parser nor affect it by setting directly. I believe it's set on the backend somehow.
https://github.com/SekoiaLab/integration/issues/652

O365 - fix category for UserLoginFailed

---

Ivanti/pulse-connect/ingest/parser.yml
Ivanti/pulse-connect/tests/login_failed.json

https://github.com/SekoiaLab/integration/issues/592
According to the [docs](https://help.ivanti.com/ps/help/en_US/IPS/vNow/em/totp-server-related-error-messages.htm) event code AUT23457 represents failed login.

Ivanti - fix event.outcome
